before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
    goarm:
      - 6
      - 7
    gomips:
      - softfloat
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
