/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSourceDevice200ResponseConfig struct for GetSourceDevice200ResponseConfig
type GetSourceDevice200ResponseConfig struct {
	ClientId string `json:"client_id"`
	Interface GetSourceDevice200ResponseConfigInterface `json:"interface"`
	Peers []GetSourceDevice200ResponseConfigPeers `json:"peers"`
	Services GetSourceDevice200ResponseConfigServices `json:"services"`
}

// NewGetSourceDevice200ResponseConfig instantiates a new GetSourceDevice200ResponseConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSourceDevice200ResponseConfig(clientId string, interface_ GetSourceDevice200ResponseConfigInterface, peers []GetSourceDevice200ResponseConfigPeers, services GetSourceDevice200ResponseConfigServices, ) *GetSourceDevice200ResponseConfig {
	this := GetSourceDevice200ResponseConfig{}
	this.ClientId = clientId
	this.Interface = interface_
	this.Peers = peers
	this.Services = services
	return &this
}

// NewGetSourceDevice200ResponseConfigWithDefaults instantiates a new GetSourceDevice200ResponseConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSourceDevice200ResponseConfigWithDefaults() *GetSourceDevice200ResponseConfig {
	this := GetSourceDevice200ResponseConfig{}
	return &this
}

// GetClientId returns the ClientId field value
func (o *GetSourceDevice200ResponseConfig) GetClientId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfig) GetClientIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *GetSourceDevice200ResponseConfig) SetClientId(v string) {
	o.ClientId = v
}

// GetInterface returns the Interface field value
func (o *GetSourceDevice200ResponseConfig) GetInterface() GetSourceDevice200ResponseConfigInterface {
	if o == nil  {
		var ret GetSourceDevice200ResponseConfigInterface
		return ret
	}

	return o.Interface
}

// GetInterfaceOk returns a tuple with the Interface field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfig) GetInterfaceOk() (*GetSourceDevice200ResponseConfigInterface, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Interface, true
}

// SetInterface sets field value
func (o *GetSourceDevice200ResponseConfig) SetInterface(v GetSourceDevice200ResponseConfigInterface) {
	o.Interface = v
}

// GetPeers returns the Peers field value
func (o *GetSourceDevice200ResponseConfig) GetPeers() []GetSourceDevice200ResponseConfigPeers {
	if o == nil  {
		var ret []GetSourceDevice200ResponseConfigPeers
		return ret
	}

	return o.Peers
}

// GetPeersOk returns a tuple with the Peers field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfig) GetPeersOk() (*[]GetSourceDevice200ResponseConfigPeers, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Peers, true
}

// SetPeers sets field value
func (o *GetSourceDevice200ResponseConfig) SetPeers(v []GetSourceDevice200ResponseConfigPeers) {
	o.Peers = v
}

// GetServices returns the Services field value
func (o *GetSourceDevice200ResponseConfig) GetServices() GetSourceDevice200ResponseConfigServices {
	if o == nil  {
		var ret GetSourceDevice200ResponseConfigServices
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfig) GetServicesOk() (*GetSourceDevice200ResponseConfigServices, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Services, true
}

// SetServices sets field value
func (o *GetSourceDevice200ResponseConfig) SetServices(v GetSourceDevice200ResponseConfigServices) {
	o.Services = v
}

func (o GetSourceDevice200ResponseConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["client_id"] = o.ClientId
	}
	if true {
		toSerialize["interface"] = o.Interface
	}
	if true {
		toSerialize["peers"] = o.Peers
	}
	if true {
		toSerialize["services"] = o.Services
	}
	return json.Marshal(toSerialize)
}

type NullableGetSourceDevice200ResponseConfig struct {
	value *GetSourceDevice200ResponseConfig
	isSet bool
}

func (v NullableGetSourceDevice200ResponseConfig) Get() *GetSourceDevice200ResponseConfig {
	return v.value
}

func (v *NullableGetSourceDevice200ResponseConfig) Set(val *GetSourceDevice200ResponseConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSourceDevice200ResponseConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSourceDevice200ResponseConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSourceDevice200ResponseConfig(val *GetSourceDevice200ResponseConfig) *NullableGetSourceDevice200ResponseConfig {
	return &NullableGetSourceDevice200ResponseConfig{value: val, isSet: true}
}

func (v NullableGetSourceDevice200ResponseConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSourceDevice200ResponseConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


