/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// HTTPRequestMethod the model 'HTTPRequestMethod'
type HTTPRequestMethod string

// List of HTTPRequestMethod
const (
	DELETE HTTPRequestMethod = "DELETE"
	GET HTTPRequestMethod = "GET"
	PATCH HTTPRequestMethod = "PATCH"
	POST HTTPRequestMethod = "POST"
	PUT HTTPRequestMethod = "PUT"
)

// All allowed values of HTTPRequestMethod enum
var AllowedHTTPRequestMethodEnumValues = []HTTPRequestMethod{
	"DELETE",
	"GET",
	"PATCH",
	"POST",
	"PUT",
}

func (v *HTTPRequestMethod) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := HTTPRequestMethod(value)
	for _, existing := range AllowedHTTPRequestMethodEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid HTTPRequestMethod", value)
}

// NewHTTPRequestMethodFromValue returns a pointer to a valid HTTPRequestMethod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewHTTPRequestMethodFromValue(v string) (*HTTPRequestMethod, error) {
	ev := HTTPRequestMethod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for HTTPRequestMethod: valid values are %v", v, AllowedHTTPRequestMethodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v HTTPRequestMethod) IsValid() bool {
	for _, existing := range AllowedHTTPRequestMethodEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to HTTPRequestMethod value
func (v HTTPRequestMethod) Ptr() *HTTPRequestMethod {
	return &v
}

type NullableHTTPRequestMethod struct {
	value *HTTPRequestMethod
	isSet bool
}

func (v NullableHTTPRequestMethod) Get() *HTTPRequestMethod {
	return v.value
}

func (v *NullableHTTPRequestMethod) Set(val *HTTPRequestMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableHTTPRequestMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableHTTPRequestMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHTTPRequestMethod(val *HTTPRequestMethod) *NullableHTTPRequestMethod {
	return &NullableHTTPRequestMethod{value: val, isSet: true}
}

func (v NullableHTTPRequestMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHTTPRequestMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

