/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetClientConfig200ResponseDenylist struct for GetClientConfig200ResponseDenylist
type GetClientConfig200ResponseDenylist struct {
	AndroidPackages *[]string `json:"android-packages,omitempty"`
	Name string `json:"name"`
	Networks *GetClientConfig200ResponseNetworks1 `json:"networks,omitempty"`
	Visible bool `json:"visible"`
}

// NewGetClientConfig200ResponseDenylist instantiates a new GetClientConfig200ResponseDenylist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientConfig200ResponseDenylist(name string, visible bool, ) *GetClientConfig200ResponseDenylist {
	this := GetClientConfig200ResponseDenylist{}
	this.Name = name
	this.Visible = visible
	return &this
}

// NewGetClientConfig200ResponseDenylistWithDefaults instantiates a new GetClientConfig200ResponseDenylist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientConfig200ResponseDenylistWithDefaults() *GetClientConfig200ResponseDenylist {
	this := GetClientConfig200ResponseDenylist{}
	return &this
}

// GetAndroidPackages returns the AndroidPackages field value if set, zero value otherwise.
func (o *GetClientConfig200ResponseDenylist) GetAndroidPackages() []string {
	if o == nil || o.AndroidPackages == nil {
		var ret []string
		return ret
	}
	return *o.AndroidPackages
}

// GetAndroidPackagesOk returns a tuple with the AndroidPackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseDenylist) GetAndroidPackagesOk() (*[]string, bool) {
	if o == nil || o.AndroidPackages == nil {
		return nil, false
	}
	return o.AndroidPackages, true
}

// HasAndroidPackages returns a boolean if a field has been set.
func (o *GetClientConfig200ResponseDenylist) HasAndroidPackages() bool {
	if o != nil && o.AndroidPackages != nil {
		return true
	}

	return false
}

// SetAndroidPackages gets a reference to the given []string and assigns it to the AndroidPackages field.
func (o *GetClientConfig200ResponseDenylist) SetAndroidPackages(v []string) {
	o.AndroidPackages = &v
}

// GetName returns the Name field value
func (o *GetClientConfig200ResponseDenylist) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseDenylist) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetClientConfig200ResponseDenylist) SetName(v string) {
	o.Name = v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *GetClientConfig200ResponseDenylist) GetNetworks() GetClientConfig200ResponseNetworks1 {
	if o == nil || o.Networks == nil {
		var ret GetClientConfig200ResponseNetworks1
		return ret
	}
	return *o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseDenylist) GetNetworksOk() (*GetClientConfig200ResponseNetworks1, bool) {
	if o == nil || o.Networks == nil {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *GetClientConfig200ResponseDenylist) HasNetworks() bool {
	if o != nil && o.Networks != nil {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given GetClientConfig200ResponseNetworks1 and assigns it to the Networks field.
func (o *GetClientConfig200ResponseDenylist) SetNetworks(v GetClientConfig200ResponseNetworks1) {
	o.Networks = &v
}

// GetVisible returns the Visible field value
func (o *GetClientConfig200ResponseDenylist) GetVisible() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseDenylist) GetVisibleOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Visible, true
}

// SetVisible sets field value
func (o *GetClientConfig200ResponseDenylist) SetVisible(v bool) {
	o.Visible = v
}

func (o GetClientConfig200ResponseDenylist) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AndroidPackages != nil {
		toSerialize["android-packages"] = o.AndroidPackages
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Networks != nil {
		toSerialize["networks"] = o.Networks
	}
	if true {
		toSerialize["visible"] = o.Visible
	}
	return json.Marshal(toSerialize)
}

type NullableGetClientConfig200ResponseDenylist struct {
	value *GetClientConfig200ResponseDenylist
	isSet bool
}

func (v NullableGetClientConfig200ResponseDenylist) Get() *GetClientConfig200ResponseDenylist {
	return v.value
}

func (v *NullableGetClientConfig200ResponseDenylist) Set(val *GetClientConfig200ResponseDenylist) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientConfig200ResponseDenylist) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientConfig200ResponseDenylist) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientConfig200ResponseDenylist(val *GetClientConfig200ResponseDenylist) *NullableGetClientConfig200ResponseDenylist {
	return &NullableGetClientConfig200ResponseDenylist{value: val, isSet: true}
}

func (v NullableGetClientConfig200ResponseDenylist) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientConfig200ResponseDenylist) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


