/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResetAccountLicense200Response struct for ResetAccountLicense200Response
type ResetAccountLicense200Response struct {
	License string `json:"license"`
}

// NewResetAccountLicense200Response instantiates a new ResetAccountLicense200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetAccountLicense200Response(license string, ) *ResetAccountLicense200Response {
	this := ResetAccountLicense200Response{}
	this.License = license
	return &this
}

// NewResetAccountLicense200ResponseWithDefaults instantiates a new ResetAccountLicense200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetAccountLicense200ResponseWithDefaults() *ResetAccountLicense200Response {
	this := ResetAccountLicense200Response{}
	return &this
}

// GetLicense returns the License field value
func (o *ResetAccountLicense200Response) GetLicense() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.License
}

// GetLicenseOk returns a tuple with the License field value
// and a boolean to check if the value has been set.
func (o *ResetAccountLicense200Response) GetLicenseOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.License, true
}

// SetLicense sets field value
func (o *ResetAccountLicense200Response) SetLicense(v string) {
	o.License = v
}

func (o ResetAccountLicense200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["license"] = o.License
	}
	return json.Marshal(toSerialize)
}

type NullableResetAccountLicense200Response struct {
	value *ResetAccountLicense200Response
	isSet bool
}

func (v NullableResetAccountLicense200Response) Get() *ResetAccountLicense200Response {
	return v.value
}

func (v *NullableResetAccountLicense200Response) Set(val *ResetAccountLicense200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableResetAccountLicense200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableResetAccountLicense200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetAccountLicense200Response(val *ResetAccountLicense200Response) *NullableResetAccountLicense200Response {
	return &NullableResetAccountLicense200Response{value: val, isSet: true}
}

func (v NullableResetAccountLicense200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetAccountLicense200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


