/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ReceiptTokenUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptTokenUpdate{}

// ReceiptTokenUpdate struct for ReceiptTokenUpdate
type ReceiptTokenUpdate struct {
	Token string `json:"token"`
	AdditionalProperties map[string]interface{}
}

type _ReceiptTokenUpdate ReceiptTokenUpdate

// NewReceiptTokenUpdate instantiates a new ReceiptTokenUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptTokenUpdate(token string) *ReceiptTokenUpdate {
	this := ReceiptTokenUpdate{}
	this.Token = token
	return &this
}

// NewReceiptTokenUpdateWithDefaults instantiates a new ReceiptTokenUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptTokenUpdateWithDefaults() *ReceiptTokenUpdate {
	this := ReceiptTokenUpdate{}
	return &this
}

// GetToken returns the Token field value
func (o *ReceiptTokenUpdate) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *ReceiptTokenUpdate) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ReceiptTokenUpdate) SetToken(v string) {
	o.Token = v
}

func (o ReceiptTokenUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptTokenUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReceiptTokenUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiptTokenUpdate := _ReceiptTokenUpdate{}

	err = json.Unmarshal(data, &varReceiptTokenUpdate)

	if err != nil {
		return err
	}

	*o = ReceiptTokenUpdate(varReceiptTokenUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReceiptTokenUpdate struct {
	value *ReceiptTokenUpdate
	isSet bool
}

func (v NullableReceiptTokenUpdate) Get() *ReceiptTokenUpdate {
	return v.value
}

func (v *NullableReceiptTokenUpdate) Set(val *ReceiptTokenUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptTokenUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptTokenUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptTokenUpdate(val *ReceiptTokenUpdate) *NullableReceiptTokenUpdate {
	return &NullableReceiptTokenUpdate{value: val, isSet: true}
}

func (v NullableReceiptTokenUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptTokenUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


