/*
Cloudflare WARP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 536
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetClientConfig200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetClientConfig200Response{}

// GetClientConfig200Response struct for GetClientConfig200Response
type GetClientConfig200Response struct {
	CaptivePortal []GetClientConfig200ResponseCaptivePortalInner `json:"captive_portal"`
	Denylist []GetClientConfig200ResponseDenylistInner `json:"denylist"`
	PremiumDataBytes float32 `json:"premium_data_bytes"`
	ReferralRewardBytes float32 `json:"referral_reward_bytes"`
	AdditionalProperties map[string]interface{}
}

type _GetClientConfig200Response GetClientConfig200Response

// NewGetClientConfig200Response instantiates a new GetClientConfig200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientConfig200Response(captivePortal []GetClientConfig200ResponseCaptivePortalInner, denylist []GetClientConfig200ResponseDenylistInner, premiumDataBytes float32, referralRewardBytes float32) *GetClientConfig200Response {
	this := GetClientConfig200Response{}
	this.CaptivePortal = captivePortal
	this.Denylist = denylist
	this.PremiumDataBytes = premiumDataBytes
	this.ReferralRewardBytes = referralRewardBytes
	return &this
}

// NewGetClientConfig200ResponseWithDefaults instantiates a new GetClientConfig200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientConfig200ResponseWithDefaults() *GetClientConfig200Response {
	this := GetClientConfig200Response{}
	return &this
}

// GetCaptivePortal returns the CaptivePortal field value
func (o *GetClientConfig200Response) GetCaptivePortal() []GetClientConfig200ResponseCaptivePortalInner {
	if o == nil {
		var ret []GetClientConfig200ResponseCaptivePortalInner
		return ret
	}

	return o.CaptivePortal
}

// GetCaptivePortalOk returns a tuple with the CaptivePortal field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200Response) GetCaptivePortalOk() ([]GetClientConfig200ResponseCaptivePortalInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.CaptivePortal, true
}

// SetCaptivePortal sets field value
func (o *GetClientConfig200Response) SetCaptivePortal(v []GetClientConfig200ResponseCaptivePortalInner) {
	o.CaptivePortal = v
}

// GetDenylist returns the Denylist field value
func (o *GetClientConfig200Response) GetDenylist() []GetClientConfig200ResponseDenylistInner {
	if o == nil {
		var ret []GetClientConfig200ResponseDenylistInner
		return ret
	}

	return o.Denylist
}

// GetDenylistOk returns a tuple with the Denylist field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200Response) GetDenylistOk() ([]GetClientConfig200ResponseDenylistInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Denylist, true
}

// SetDenylist sets field value
func (o *GetClientConfig200Response) SetDenylist(v []GetClientConfig200ResponseDenylistInner) {
	o.Denylist = v
}

// GetPremiumDataBytes returns the PremiumDataBytes field value
func (o *GetClientConfig200Response) GetPremiumDataBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PremiumDataBytes
}

// GetPremiumDataBytesOk returns a tuple with the PremiumDataBytes field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200Response) GetPremiumDataBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PremiumDataBytes, true
}

// SetPremiumDataBytes sets field value
func (o *GetClientConfig200Response) SetPremiumDataBytes(v float32) {
	o.PremiumDataBytes = v
}

// GetReferralRewardBytes returns the ReferralRewardBytes field value
func (o *GetClientConfig200Response) GetReferralRewardBytes() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ReferralRewardBytes
}

// GetReferralRewardBytesOk returns a tuple with the ReferralRewardBytes field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200Response) GetReferralRewardBytesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralRewardBytes, true
}

// SetReferralRewardBytes sets field value
func (o *GetClientConfig200Response) SetReferralRewardBytes(v float32) {
	o.ReferralRewardBytes = v
}

func (o GetClientConfig200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetClientConfig200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["captive_portal"] = o.CaptivePortal
	toSerialize["denylist"] = o.Denylist
	toSerialize["premium_data_bytes"] = o.PremiumDataBytes
	toSerialize["referral_reward_bytes"] = o.ReferralRewardBytes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetClientConfig200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"captive_portal",
		"denylist",
		"premium_data_bytes",
		"referral_reward_bytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetClientConfig200Response := _GetClientConfig200Response{}

	err = json.Unmarshal(data, &varGetClientConfig200Response)

	if err != nil {
		return err
	}

	*o = GetClientConfig200Response(varGetClientConfig200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "captive_portal")
		delete(additionalProperties, "denylist")
		delete(additionalProperties, "premium_data_bytes")
		delete(additionalProperties, "referral_reward_bytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetClientConfig200Response struct {
	value *GetClientConfig200Response
	isSet bool
}

func (v NullableGetClientConfig200Response) Get() *GetClientConfig200Response {
	return v.value
}

func (v *NullableGetClientConfig200Response) Set(val *GetClientConfig200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientConfig200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientConfig200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientConfig200Response(val *GetClientConfig200Response) *NullableGetClientConfig200Response {
	return &NullableGetClientConfig200Response{value: val, isSet: true}
}

func (v NullableGetClientConfig200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientConfig200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


