/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateSourceDevice200ResponseAccount struct for UpdateSourceDevice200ResponseAccount
type UpdateSourceDevice200ResponseAccount struct {
	AccountType string `json:"account_type"`
	Created string `json:"created"`
	Id string `json:"id"`
	License string `json:"license"`
	PremiumData float32 `json:"premium_data"`
	Quota float32 `json:"quota"`
	ReferralCount float32 `json:"referral_count"`
	ReferralRenewalCountdown float32 `json:"referral_renewal_countdown"`
	Role string `json:"role"`
	Updated string `json:"updated"`
	WarpPlus bool `json:"warp_plus"`
}

// NewUpdateSourceDevice200ResponseAccount instantiates a new UpdateSourceDevice200ResponseAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSourceDevice200ResponseAccount(accountType string, created string, id string, license string, premiumData float32, quota float32, referralCount float32, referralRenewalCountdown float32, role string, updated string, warpPlus bool, ) *UpdateSourceDevice200ResponseAccount {
	this := UpdateSourceDevice200ResponseAccount{}
	this.AccountType = accountType
	this.Created = created
	this.Id = id
	this.License = license
	this.PremiumData = premiumData
	this.Quota = quota
	this.ReferralCount = referralCount
	this.ReferralRenewalCountdown = referralRenewalCountdown
	this.Role = role
	this.Updated = updated
	this.WarpPlus = warpPlus
	return &this
}

// NewUpdateSourceDevice200ResponseAccountWithDefaults instantiates a new UpdateSourceDevice200ResponseAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSourceDevice200ResponseAccountWithDefaults() *UpdateSourceDevice200ResponseAccount {
	this := UpdateSourceDevice200ResponseAccount{}
	return &this
}

// GetAccountType returns the AccountType field value
func (o *UpdateSourceDevice200ResponseAccount) GetAccountType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetAccountTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetAccountType(v string) {
	o.AccountType = v
}

// GetCreated returns the Created field value
func (o *UpdateSourceDevice200ResponseAccount) GetCreated() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetCreatedOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetCreated(v string) {
	o.Created = v
}

// GetId returns the Id field value
func (o *UpdateSourceDevice200ResponseAccount) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetId(v string) {
	o.Id = v
}

// GetLicense returns the License field value
func (o *UpdateSourceDevice200ResponseAccount) GetLicense() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.License
}

// GetLicenseOk returns a tuple with the License field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetLicenseOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.License, true
}

// SetLicense sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetLicense(v string) {
	o.License = v
}

// GetPremiumData returns the PremiumData field value
func (o *UpdateSourceDevice200ResponseAccount) GetPremiumData() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.PremiumData
}

// GetPremiumDataOk returns a tuple with the PremiumData field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetPremiumDataOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PremiumData, true
}

// SetPremiumData sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetPremiumData(v float32) {
	o.PremiumData = v
}

// GetQuota returns the Quota field value
func (o *UpdateSourceDevice200ResponseAccount) GetQuota() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetQuotaOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetQuota(v float32) {
	o.Quota = v
}

// GetReferralCount returns the ReferralCount field value
func (o *UpdateSourceDevice200ResponseAccount) GetReferralCount() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.ReferralCount
}

// GetReferralCountOk returns a tuple with the ReferralCount field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetReferralCountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReferralCount, true
}

// SetReferralCount sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetReferralCount(v float32) {
	o.ReferralCount = v
}

// GetReferralRenewalCountdown returns the ReferralRenewalCountdown field value
func (o *UpdateSourceDevice200ResponseAccount) GetReferralRenewalCountdown() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.ReferralRenewalCountdown
}

// GetReferralRenewalCountdownOk returns a tuple with the ReferralRenewalCountdown field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetReferralRenewalCountdownOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReferralRenewalCountdown, true
}

// SetReferralRenewalCountdown sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetReferralRenewalCountdown(v float32) {
	o.ReferralRenewalCountdown = v
}

// GetRole returns the Role field value
func (o *UpdateSourceDevice200ResponseAccount) GetRole() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetRoleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetRole(v string) {
	o.Role = v
}

// GetUpdated returns the Updated field value
func (o *UpdateSourceDevice200ResponseAccount) GetUpdated() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetUpdatedOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetUpdated(v string) {
	o.Updated = v
}

// GetWarpPlus returns the WarpPlus field value
func (o *UpdateSourceDevice200ResponseAccount) GetWarpPlus() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.WarpPlus
}

// GetWarpPlusOk returns a tuple with the WarpPlus field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetWarpPlusOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WarpPlus, true
}

// SetWarpPlus sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetWarpPlus(v bool) {
	o.WarpPlus = v
}

func (o UpdateSourceDevice200ResponseAccount) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["account_type"] = o.AccountType
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["license"] = o.License
	}
	if true {
		toSerialize["premium_data"] = o.PremiumData
	}
	if true {
		toSerialize["quota"] = o.Quota
	}
	if true {
		toSerialize["referral_count"] = o.ReferralCount
	}
	if true {
		toSerialize["referral_renewal_countdown"] = o.ReferralRenewalCountdown
	}
	if true {
		toSerialize["role"] = o.Role
	}
	if true {
		toSerialize["updated"] = o.Updated
	}
	if true {
		toSerialize["warp_plus"] = o.WarpPlus
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateSourceDevice200ResponseAccount struct {
	value *UpdateSourceDevice200ResponseAccount
	isSet bool
}

func (v NullableUpdateSourceDevice200ResponseAccount) Get() *UpdateSourceDevice200ResponseAccount {
	return v.value
}

func (v *NullableUpdateSourceDevice200ResponseAccount) Set(val *UpdateSourceDevice200ResponseAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSourceDevice200ResponseAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSourceDevice200ResponseAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSourceDevice200ResponseAccount(val *UpdateSourceDevice200ResponseAccount) *NullableUpdateSourceDevice200ResponseAccount {
	return &NullableUpdateSourceDevice200ResponseAccount{value: val, isSet: true}
}

func (v NullableUpdateSourceDevice200ResponseAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSourceDevice200ResponseAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


