/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetClientConfig200ResponseNetworks1V6 struct for GetClientConfig200ResponseNetworks1V6
type GetClientConfig200ResponseNetworks1V6 struct {
	Address string `json:"address"`
	Prefix float32 `json:"prefix"`
}

// NewGetClientConfig200ResponseNetworks1V6 instantiates a new GetClientConfig200ResponseNetworks1V6 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientConfig200ResponseNetworks1V6(address string, prefix float32, ) *GetClientConfig200ResponseNetworks1V6 {
	this := GetClientConfig200ResponseNetworks1V6{}
	this.Address = address
	this.Prefix = prefix
	return &this
}

// NewGetClientConfig200ResponseNetworks1V6WithDefaults instantiates a new GetClientConfig200ResponseNetworks1V6 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientConfig200ResponseNetworks1V6WithDefaults() *GetClientConfig200ResponseNetworks1V6 {
	this := GetClientConfig200ResponseNetworks1V6{}
	return &this
}

// GetAddress returns the Address field value
func (o *GetClientConfig200ResponseNetworks1V6) GetAddress() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseNetworks1V6) GetAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *GetClientConfig200ResponseNetworks1V6) SetAddress(v string) {
	o.Address = v
}

// GetPrefix returns the Prefix field value
func (o *GetClientConfig200ResponseNetworks1V6) GetPrefix() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseNetworks1V6) GetPrefixOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *GetClientConfig200ResponseNetworks1V6) SetPrefix(v float32) {
	o.Prefix = v
}

func (o GetClientConfig200ResponseNetworks1V6) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["address"] = o.Address
	}
	if true {
		toSerialize["prefix"] = o.Prefix
	}
	return json.Marshal(toSerialize)
}

type NullableGetClientConfig200ResponseNetworks1V6 struct {
	value *GetClientConfig200ResponseNetworks1V6
	isSet bool
}

func (v NullableGetClientConfig200ResponseNetworks1V6) Get() *GetClientConfig200ResponseNetworks1V6 {
	return v.value
}

func (v *NullableGetClientConfig200ResponseNetworks1V6) Set(val *GetClientConfig200ResponseNetworks1V6) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientConfig200ResponseNetworks1V6) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientConfig200ResponseNetworks1V6) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientConfig200ResponseNetworks1V6(val *GetClientConfig200ResponseNetworks1V6) *NullableGetClientConfig200ResponseNetworks1V6 {
	return &NullableGetClientConfig200ResponseNetworks1V6{value: val, isSet: true}
}

func (v NullableGetClientConfig200ResponseNetworks1V6) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientConfig200ResponseNetworks1V6) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


