/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OverrideCodes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OverrideCodes{}

// OverrideCodes struct for OverrideCodes
type OverrideCodes struct {
	DisableForTime *DisableForTime `json:"disable_for_time,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OverrideCodes OverrideCodes

// NewOverrideCodes instantiates a new OverrideCodes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverrideCodes() *OverrideCodes {
	this := OverrideCodes{}
	return &this
}

// NewOverrideCodesWithDefaults instantiates a new OverrideCodes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverrideCodesWithDefaults() *OverrideCodes {
	this := OverrideCodes{}
	return &this
}

// GetDisableForTime returns the DisableForTime field value if set, zero value otherwise.
func (o *OverrideCodes) GetDisableForTime() DisableForTime {
	if o == nil || IsNil(o.DisableForTime) {
		var ret DisableForTime
		return ret
	}
	return *o.DisableForTime
}

// GetDisableForTimeOk returns a tuple with the DisableForTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverrideCodes) GetDisableForTimeOk() (*DisableForTime, bool) {
	if o == nil || IsNil(o.DisableForTime) {
		return nil, false
	}
	return o.DisableForTime, true
}

// HasDisableForTime returns a boolean if a field has been set.
func (o *OverrideCodes) HasDisableForTime() bool {
	if o != nil && !IsNil(o.DisableForTime) {
		return true
	}

	return false
}

// SetDisableForTime gets a reference to the given DisableForTime and assigns it to the DisableForTime field.
func (o *OverrideCodes) SetDisableForTime(v DisableForTime) {
	o.DisableForTime = &v
}

func (o OverrideCodes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverrideCodes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisableForTime) {
		toSerialize["disable_for_time"] = o.DisableForTime
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OverrideCodes) UnmarshalJSON(data []byte) (err error) {
	varOverrideCodes := _OverrideCodes{}

	err = json.Unmarshal(data, &varOverrideCodes)

	if err != nil {
		return err
	}

	*o = OverrideCodes(varOverrideCodes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "disable_for_time")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOverrideCodes struct {
	value *OverrideCodes
	isSet bool
}

func (v NullableOverrideCodes) Get() *OverrideCodes {
	return v.value
}

func (v *NullableOverrideCodes) Set(val *OverrideCodes) {
	v.value = val
	v.isSet = true
}

func (v NullableOverrideCodes) IsSet() bool {
	return v.isSet
}

func (v *NullableOverrideCodes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverrideCodes(val *OverrideCodes) *NullableOverrideCodes {
	return &NullableOverrideCodes{value: val, isSet: true}
}

func (v NullableOverrideCodes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverrideCodes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


