/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateSourceDeviceRequest struct for UpdateSourceDeviceRequest
type UpdateSourceDeviceRequest struct {
	Key string `json:"key"`
}
