/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetSourceDevice200ResponseConfigServices struct for GetSourceDevice200ResponseConfigServices
type GetSourceDevice200ResponseConfigServices struct {
	HttpProxy string `json:"http_proxy"`
}
