/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the UpdateAccount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAccount200Response{}

// UpdateAccount200Response struct for UpdateAccount200Response
type UpdateAccount200Response struct {
	Created time.Time `json:"created"`
	Id string `json:"id"`
	PremiumData int64 `json:"premium_data"`
	Quota int64 `json:"quota"`
	ReferralCount int32 `json:"referral_count"`
	ReferralRenewalCountdown int32 `json:"referral_renewal_countdown"`
	Role string `json:"role"`
	Updated time.Time `json:"updated"`
	WarpPlus bool `json:"warp_plus"`
	AdditionalProperties map[string]interface{}
}

type _UpdateAccount200Response UpdateAccount200Response

// NewUpdateAccount200Response instantiates a new UpdateAccount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAccount200Response(created time.Time, id string, premiumData int64, quota int64, referralCount int32, referralRenewalCountdown int32, role string, updated time.Time, warpPlus bool) *UpdateAccount200Response {
	this := UpdateAccount200Response{}
	this.Created = created
	this.Id = id
	this.PremiumData = premiumData
	this.Quota = quota
	this.ReferralCount = referralCount
	this.ReferralRenewalCountdown = referralRenewalCountdown
	this.Role = role
	this.Updated = updated
	this.WarpPlus = warpPlus
	return &this
}

// NewUpdateAccount200ResponseWithDefaults instantiates a new UpdateAccount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAccount200ResponseWithDefaults() *UpdateAccount200Response {
	this := UpdateAccount200Response{}
	return &this
}

// GetCreated returns the Created field value
func (o *UpdateAccount200Response) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *UpdateAccount200Response) SetCreated(v time.Time) {
	o.Created = v
}

// GetId returns the Id field value
func (o *UpdateAccount200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateAccount200Response) SetId(v string) {
	o.Id = v
}

// GetPremiumData returns the PremiumData field value
func (o *UpdateAccount200Response) GetPremiumData() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PremiumData
}

// GetPremiumDataOk returns a tuple with the PremiumData field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetPremiumDataOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PremiumData, true
}

// SetPremiumData sets field value
func (o *UpdateAccount200Response) SetPremiumData(v int64) {
	o.PremiumData = v
}

// GetQuota returns the Quota field value
func (o *UpdateAccount200Response) GetQuota() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetQuotaOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *UpdateAccount200Response) SetQuota(v int64) {
	o.Quota = v
}

// GetReferralCount returns the ReferralCount field value
func (o *UpdateAccount200Response) GetReferralCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReferralCount
}

// GetReferralCountOk returns a tuple with the ReferralCount field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetReferralCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralCount, true
}

// SetReferralCount sets field value
func (o *UpdateAccount200Response) SetReferralCount(v int32) {
	o.ReferralCount = v
}

// GetReferralRenewalCountdown returns the ReferralRenewalCountdown field value
func (o *UpdateAccount200Response) GetReferralRenewalCountdown() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReferralRenewalCountdown
}

// GetReferralRenewalCountdownOk returns a tuple with the ReferralRenewalCountdown field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetReferralRenewalCountdownOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralRenewalCountdown, true
}

// SetReferralRenewalCountdown sets field value
func (o *UpdateAccount200Response) SetReferralRenewalCountdown(v int32) {
	o.ReferralRenewalCountdown = v
}

// GetRole returns the Role field value
func (o *UpdateAccount200Response) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UpdateAccount200Response) SetRole(v string) {
	o.Role = v
}

// GetUpdated returns the Updated field value
func (o *UpdateAccount200Response) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *UpdateAccount200Response) SetUpdated(v time.Time) {
	o.Updated = v
}

// GetWarpPlus returns the WarpPlus field value
func (o *UpdateAccount200Response) GetWarpPlus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.WarpPlus
}

// GetWarpPlusOk returns a tuple with the WarpPlus field value
// and a boolean to check if the value has been set.
func (o *UpdateAccount200Response) GetWarpPlusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarpPlus, true
}

// SetWarpPlus sets field value
func (o *UpdateAccount200Response) SetWarpPlus(v bool) {
	o.WarpPlus = v
}

func (o UpdateAccount200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAccount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["id"] = o.Id
	toSerialize["premium_data"] = o.PremiumData
	toSerialize["quota"] = o.Quota
	toSerialize["referral_count"] = o.ReferralCount
	toSerialize["referral_renewal_countdown"] = o.ReferralRenewalCountdown
	toSerialize["role"] = o.Role
	toSerialize["updated"] = o.Updated
	toSerialize["warp_plus"] = o.WarpPlus

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateAccount200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"id",
		"premium_data",
		"quota",
		"referral_count",
		"referral_renewal_countdown",
		"role",
		"updated",
		"warp_plus",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAccount200Response := _UpdateAccount200Response{}

	err = json.Unmarshal(data, &varUpdateAccount200Response)

	if err != nil {
		return err
	}

	*o = UpdateAccount200Response(varUpdateAccount200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created")
		delete(additionalProperties, "id")
		delete(additionalProperties, "premium_data")
		delete(additionalProperties, "quota")
		delete(additionalProperties, "referral_count")
		delete(additionalProperties, "referral_renewal_countdown")
		delete(additionalProperties, "role")
		delete(additionalProperties, "updated")
		delete(additionalProperties, "warp_plus")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateAccount200Response struct {
	value *UpdateAccount200Response
	isSet bool
}

func (v NullableUpdateAccount200Response) Get() *UpdateAccount200Response {
	return v.value
}

func (v *NullableUpdateAccount200Response) Set(val *UpdateAccount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAccount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAccount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAccount200Response(val *UpdateAccount200Response) *NullableUpdateAccount200Response {
	return &NullableUpdateAccount200Response{value: val, isSet: true}
}

func (v NullableUpdateAccount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAccount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


