/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSourceDevice200ResponseConfigInterfaceAddresses struct for GetSourceDevice200ResponseConfigInterfaceAddresses
type GetSourceDevice200ResponseConfigInterfaceAddresses struct {
	V4 string `json:"v4"`
	V6 string `json:"v6"`
}

// NewGetSourceDevice200ResponseConfigInterfaceAddresses instantiates a new GetSourceDevice200ResponseConfigInterfaceAddresses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSourceDevice200ResponseConfigInterfaceAddresses(v4 string, v6 string, ) *GetSourceDevice200ResponseConfigInterfaceAddresses {
	this := GetSourceDevice200ResponseConfigInterfaceAddresses{}
	this.V4 = v4
	this.V6 = v6
	return &this
}

// NewGetSourceDevice200ResponseConfigInterfaceAddressesWithDefaults instantiates a new GetSourceDevice200ResponseConfigInterfaceAddresses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSourceDevice200ResponseConfigInterfaceAddressesWithDefaults() *GetSourceDevice200ResponseConfigInterfaceAddresses {
	this := GetSourceDevice200ResponseConfigInterfaceAddresses{}
	return &this
}

// GetV4 returns the V4 field value
func (o *GetSourceDevice200ResponseConfigInterfaceAddresses) GetV4() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.V4
}

// GetV4Ok returns a tuple with the V4 field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfigInterfaceAddresses) GetV4Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.V4, true
}

// SetV4 sets field value
func (o *GetSourceDevice200ResponseConfigInterfaceAddresses) SetV4(v string) {
	o.V4 = v
}

// GetV6 returns the V6 field value
func (o *GetSourceDevice200ResponseConfigInterfaceAddresses) GetV6() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.V6
}

// GetV6Ok returns a tuple with the V6 field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfigInterfaceAddresses) GetV6Ok() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.V6, true
}

// SetV6 sets field value
func (o *GetSourceDevice200ResponseConfigInterfaceAddresses) SetV6(v string) {
	o.V6 = v
}

func (o GetSourceDevice200ResponseConfigInterfaceAddresses) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["v4"] = o.V4
	}
	if true {
		toSerialize["v6"] = o.V6
	}
	return json.Marshal(toSerialize)
}

type NullableGetSourceDevice200ResponseConfigInterfaceAddresses struct {
	value *GetSourceDevice200ResponseConfigInterfaceAddresses
	isSet bool
}

func (v NullableGetSourceDevice200ResponseConfigInterfaceAddresses) Get() *GetSourceDevice200ResponseConfigInterfaceAddresses {
	return v.value
}

func (v *NullableGetSourceDevice200ResponseConfigInterfaceAddresses) Set(val *GetSourceDevice200ResponseConfigInterfaceAddresses) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSourceDevice200ResponseConfigInterfaceAddresses) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSourceDevice200ResponseConfigInterfaceAddresses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSourceDevice200ResponseConfigInterfaceAddresses(val *GetSourceDevice200ResponseConfigInterfaceAddresses) *NullableGetSourceDevice200ResponseConfigInterfaceAddresses {
	return &NullableGetSourceDevice200ResponseConfigInterfaceAddresses{value: val, isSet: true}
}

func (v NullableGetSourceDevice200ResponseConfigInterfaceAddresses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSourceDevice200ResponseConfigInterfaceAddresses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


