/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetSourceDevice200ResponseConfigPeers struct for GetSourceDevice200ResponseConfigPeers
type GetSourceDevice200ResponseConfigPeers struct {
	Endpoint GetSourceDevice200ResponseConfigEndpoint `json:"endpoint"`
	PublicKey string `json:"public_key"`
}

// NewGetSourceDevice200ResponseConfigPeers instantiates a new GetSourceDevice200ResponseConfigPeers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSourceDevice200ResponseConfigPeers(endpoint GetSourceDevice200ResponseConfigEndpoint, publicKey string, ) *GetSourceDevice200ResponseConfigPeers {
	this := GetSourceDevice200ResponseConfigPeers{}
	this.Endpoint = endpoint
	this.PublicKey = publicKey
	return &this
}

// NewGetSourceDevice200ResponseConfigPeersWithDefaults instantiates a new GetSourceDevice200ResponseConfigPeers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSourceDevice200ResponseConfigPeersWithDefaults() *GetSourceDevice200ResponseConfigPeers {
	this := GetSourceDevice200ResponseConfigPeers{}
	return &this
}

// GetEndpoint returns the Endpoint field value
func (o *GetSourceDevice200ResponseConfigPeers) GetEndpoint() GetSourceDevice200ResponseConfigEndpoint {
	if o == nil  {
		var ret GetSourceDevice200ResponseConfigEndpoint
		return ret
	}

	return o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfigPeers) GetEndpointOk() (*GetSourceDevice200ResponseConfigEndpoint, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Endpoint, true
}

// SetEndpoint sets field value
func (o *GetSourceDevice200ResponseConfigPeers) SetEndpoint(v GetSourceDevice200ResponseConfigEndpoint) {
	o.Endpoint = v
}

// GetPublicKey returns the PublicKey field value
func (o *GetSourceDevice200ResponseConfigPeers) GetPublicKey() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200ResponseConfigPeers) GetPublicKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *GetSourceDevice200ResponseConfigPeers) SetPublicKey(v string) {
	o.PublicKey = v
}

func (o GetSourceDevice200ResponseConfigPeers) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["endpoint"] = o.Endpoint
	}
	if true {
		toSerialize["public_key"] = o.PublicKey
	}
	return json.Marshal(toSerialize)
}

type NullableGetSourceDevice200ResponseConfigPeers struct {
	value *GetSourceDevice200ResponseConfigPeers
	isSet bool
}

func (v NullableGetSourceDevice200ResponseConfigPeers) Get() *GetSourceDevice200ResponseConfigPeers {
	return v.value
}

func (v *NullableGetSourceDevice200ResponseConfigPeers) Set(val *GetSourceDevice200ResponseConfigPeers) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSourceDevice200ResponseConfigPeers) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSourceDevice200ResponseConfigPeers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSourceDevice200ResponseConfigPeers(val *GetSourceDevice200ResponseConfigPeers) *NullableGetSourceDevice200ResponseConfigPeers {
	return &NullableGetSourceDevice200ResponseConfigPeers{value: val, isSet: true}
}

func (v NullableGetSourceDevice200ResponseConfigPeers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSourceDevice200ResponseConfigPeers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


