/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetBoundDevices200Response struct for GetBoundDevices200Response
type GetBoundDevices200Response struct {
	Activated string `json:"activated"`
	Active bool `json:"active"`
	Created string `json:"created"`
	Id string `json:"id"`
	Model string `json:"model"`
	Name string `json:"name,omitempty"`
	Role string `json:"role"`
	Type string `json:"type"`
}
