/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClientConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientConfig{}

// ClientConfig struct for ClientConfig
type ClientConfig struct {
	Denylist []ClientConfigDenylistInner `json:"denylist"`
	CaptivePortal []CaptivePortal `json:"captive_portal"`
	PremiumDataBytes int64 `json:"premium_data_bytes"`
	ReferralRewardBytes int64 `json:"referral_reward_bytes"`
	AdditionalProperties map[string]interface{}
}

type _ClientConfig ClientConfig

// NewClientConfig instantiates a new ClientConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientConfig(denylist []ClientConfigDenylistInner, captivePortal []CaptivePortal, premiumDataBytes int64, referralRewardBytes int64) *ClientConfig {
	this := ClientConfig{}
	this.Denylist = denylist
	this.CaptivePortal = captivePortal
	this.PremiumDataBytes = premiumDataBytes
	this.ReferralRewardBytes = referralRewardBytes
	return &this
}

// NewClientConfigWithDefaults instantiates a new ClientConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientConfigWithDefaults() *ClientConfig {
	this := ClientConfig{}
	return &this
}

// GetDenylist returns the Denylist field value
func (o *ClientConfig) GetDenylist() []ClientConfigDenylistInner {
	if o == nil {
		var ret []ClientConfigDenylistInner
		return ret
	}

	return o.Denylist
}

// GetDenylistOk returns a tuple with the Denylist field value
// and a boolean to check if the value has been set.
func (o *ClientConfig) GetDenylistOk() ([]ClientConfigDenylistInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Denylist, true
}

// SetDenylist sets field value
func (o *ClientConfig) SetDenylist(v []ClientConfigDenylistInner) {
	o.Denylist = v
}

// GetCaptivePortal returns the CaptivePortal field value
func (o *ClientConfig) GetCaptivePortal() []CaptivePortal {
	if o == nil {
		var ret []CaptivePortal
		return ret
	}

	return o.CaptivePortal
}

// GetCaptivePortalOk returns a tuple with the CaptivePortal field value
// and a boolean to check if the value has been set.
func (o *ClientConfig) GetCaptivePortalOk() ([]CaptivePortal, bool) {
	if o == nil {
		return nil, false
	}
	return o.CaptivePortal, true
}

// SetCaptivePortal sets field value
func (o *ClientConfig) SetCaptivePortal(v []CaptivePortal) {
	o.CaptivePortal = v
}

// GetPremiumDataBytes returns the PremiumDataBytes field value
func (o *ClientConfig) GetPremiumDataBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PremiumDataBytes
}

// GetPremiumDataBytesOk returns a tuple with the PremiumDataBytes field value
// and a boolean to check if the value has been set.
func (o *ClientConfig) GetPremiumDataBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PremiumDataBytes, true
}

// SetPremiumDataBytes sets field value
func (o *ClientConfig) SetPremiumDataBytes(v int64) {
	o.PremiumDataBytes = v
}

// GetReferralRewardBytes returns the ReferralRewardBytes field value
func (o *ClientConfig) GetReferralRewardBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ReferralRewardBytes
}

// GetReferralRewardBytesOk returns a tuple with the ReferralRewardBytes field value
// and a boolean to check if the value has been set.
func (o *ClientConfig) GetReferralRewardBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralRewardBytes, true
}

// SetReferralRewardBytes sets field value
func (o *ClientConfig) SetReferralRewardBytes(v int64) {
	o.ReferralRewardBytes = v
}

func (o ClientConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["denylist"] = o.Denylist
	toSerialize["captive_portal"] = o.CaptivePortal
	toSerialize["premium_data_bytes"] = o.PremiumDataBytes
	toSerialize["referral_reward_bytes"] = o.ReferralRewardBytes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClientConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"denylist",
		"captive_portal",
		"premium_data_bytes",
		"referral_reward_bytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientConfig := _ClientConfig{}

	err = json.Unmarshal(data, &varClientConfig)

	if err != nil {
		return err
	}

	*o = ClientConfig(varClientConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "denylist")
		delete(additionalProperties, "captive_portal")
		delete(additionalProperties, "premium_data_bytes")
		delete(additionalProperties, "referral_reward_bytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClientConfig struct {
	value *ClientConfig
	isSet bool
}

func (v NullableClientConfig) Get() *ClientConfig {
	return v.value
}

func (v *NullableClientConfig) Set(val *ClientConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableClientConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableClientConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientConfig(val *ClientConfig) *NullableClientConfig {
	return &NullableClientConfig{value: val, isSet: true}
}

func (v NullableClientConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


