/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetClientConfig200ResponseNetworksV4 struct for GetClientConfig200ResponseNetworksV4
type GetClientConfig200ResponseNetworksV4 struct {
	Address string `json:"address"`
	Netmask string `json:"netmask"`
}
