/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateSourceDeviceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSourceDeviceRequest{}

// UpdateSourceDeviceRequest struct for UpdateSourceDeviceRequest
type UpdateSourceDeviceRequest struct {
	Key *string `json:"key,omitempty"`
	KeyType *string `json:"key_type,omitempty"`
	TunnelType *string `json:"tunnel_type,omitempty"`
	FcmToken *string `json:"fcm_token,omitempty"`
	Name *string `json:"name,omitempty"`
	OsVersion *string `json:"os_version,omitempty"`
	Manufacturer *string `json:"manufacturer,omitempty"`
	Model *string `json:"model,omitempty"`
	DeviceId *string `json:"device_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateSourceDeviceRequest UpdateSourceDeviceRequest

// NewUpdateSourceDeviceRequest instantiates a new UpdateSourceDeviceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSourceDeviceRequest() *UpdateSourceDeviceRequest {
	this := UpdateSourceDeviceRequest{}
	return &this
}

// NewUpdateSourceDeviceRequestWithDefaults instantiates a new UpdateSourceDeviceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSourceDeviceRequestWithDefaults() *UpdateSourceDeviceRequest {
	this := UpdateSourceDeviceRequest{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *UpdateSourceDeviceRequest) SetKey(v string) {
	o.Key = &v
}

// GetKeyType returns the KeyType field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetKeyType() string {
	if o == nil || IsNil(o.KeyType) {
		var ret string
		return ret
	}
	return *o.KeyType
}

// GetKeyTypeOk returns a tuple with the KeyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetKeyTypeOk() (*string, bool) {
	if o == nil || IsNil(o.KeyType) {
		return nil, false
	}
	return o.KeyType, true
}

// HasKeyType returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasKeyType() bool {
	if o != nil && !IsNil(o.KeyType) {
		return true
	}

	return false
}

// SetKeyType gets a reference to the given string and assigns it to the KeyType field.
func (o *UpdateSourceDeviceRequest) SetKeyType(v string) {
	o.KeyType = &v
}

// GetTunnelType returns the TunnelType field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetTunnelType() string {
	if o == nil || IsNil(o.TunnelType) {
		var ret string
		return ret
	}
	return *o.TunnelType
}

// GetTunnelTypeOk returns a tuple with the TunnelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetTunnelTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TunnelType) {
		return nil, false
	}
	return o.TunnelType, true
}

// HasTunnelType returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasTunnelType() bool {
	if o != nil && !IsNil(o.TunnelType) {
		return true
	}

	return false
}

// SetTunnelType gets a reference to the given string and assigns it to the TunnelType field.
func (o *UpdateSourceDeviceRequest) SetTunnelType(v string) {
	o.TunnelType = &v
}

// GetFcmToken returns the FcmToken field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetFcmToken() string {
	if o == nil || IsNil(o.FcmToken) {
		var ret string
		return ret
	}
	return *o.FcmToken
}

// GetFcmTokenOk returns a tuple with the FcmToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetFcmTokenOk() (*string, bool) {
	if o == nil || IsNil(o.FcmToken) {
		return nil, false
	}
	return o.FcmToken, true
}

// HasFcmToken returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasFcmToken() bool {
	if o != nil && !IsNil(o.FcmToken) {
		return true
	}

	return false
}

// SetFcmToken gets a reference to the given string and assigns it to the FcmToken field.
func (o *UpdateSourceDeviceRequest) SetFcmToken(v string) {
	o.FcmToken = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateSourceDeviceRequest) SetName(v string) {
	o.Name = &v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetOsVersion() string {
	if o == nil || IsNil(o.OsVersion) {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetOsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OsVersion) {
		return nil, false
	}
	return o.OsVersion, true
}

// HasOsVersion returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasOsVersion() bool {
	if o != nil && !IsNil(o.OsVersion) {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *UpdateSourceDeviceRequest) SetOsVersion(v string) {
	o.OsVersion = &v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer) {
		var ret string
		return ret
	}
	return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetManufacturerOk() (*string, bool) {
	if o == nil || IsNil(o.Manufacturer) {
		return nil, false
	}
	return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasManufacturer() bool {
	if o != nil && !IsNil(o.Manufacturer) {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given string and assigns it to the Manufacturer field.
func (o *UpdateSourceDeviceRequest) SetManufacturer(v string) {
	o.Manufacturer = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *UpdateSourceDeviceRequest) SetModel(v string) {
	o.Model = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *UpdateSourceDeviceRequest) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceDeviceRequest) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *UpdateSourceDeviceRequest) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *UpdateSourceDeviceRequest) SetDeviceId(v string) {
	o.DeviceId = &v
}

func (o UpdateSourceDeviceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSourceDeviceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.KeyType) {
		toSerialize["key_type"] = o.KeyType
	}
	if !IsNil(o.TunnelType) {
		toSerialize["tunnel_type"] = o.TunnelType
	}
	if !IsNil(o.FcmToken) {
		toSerialize["fcm_token"] = o.FcmToken
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OsVersion) {
		toSerialize["os_version"] = o.OsVersion
	}
	if !IsNil(o.Manufacturer) {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.DeviceId) {
		toSerialize["device_id"] = o.DeviceId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateSourceDeviceRequest) UnmarshalJSON(data []byte) (err error) {
	varUpdateSourceDeviceRequest := _UpdateSourceDeviceRequest{}

	err = json.Unmarshal(data, &varUpdateSourceDeviceRequest)

	if err != nil {
		return err
	}

	*o = UpdateSourceDeviceRequest(varUpdateSourceDeviceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "key_type")
		delete(additionalProperties, "tunnel_type")
		delete(additionalProperties, "fcm_token")
		delete(additionalProperties, "name")
		delete(additionalProperties, "os_version")
		delete(additionalProperties, "manufacturer")
		delete(additionalProperties, "model")
		delete(additionalProperties, "device_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateSourceDeviceRequest struct {
	value *UpdateSourceDeviceRequest
	isSet bool
}

func (v NullableUpdateSourceDeviceRequest) Get() *UpdateSourceDeviceRequest {
	return v.value
}

func (v *NullableUpdateSourceDeviceRequest) Set(val *UpdateSourceDeviceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSourceDeviceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSourceDeviceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSourceDeviceRequest(val *UpdateSourceDeviceRequest) *NullableUpdateSourceDeviceRequest {
	return &NullableUpdateSourceDeviceRequest{value: val, isSet: true}
}

func (v NullableUpdateSourceDeviceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSourceDeviceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


