/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetSourceDevice200ResponseConfig struct for GetSourceDevice200ResponseConfig
type GetSourceDevice200ResponseConfig struct {
	ClientId string `json:"client_id"`
	Interface GetSourceDevice200ResponseConfigInterface `json:"interface"`
	Peers []GetSourceDevice200ResponseConfigPeers `json:"peers"`
	Services GetSourceDevice200ResponseConfigServices `json:"services"`
}
