/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Policy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Policy{}

// Policy struct for Policy
type Policy struct {
	Organization *string `json:"organization,omitempty"`
	Enable *bool `json:"enable,omitempty"`
	ServiceMode *AppMode `json:"service_mode,omitempty"`
	ServiceModeV2 *ServiceMode `json:"service_mode_v2,omitempty"`
	GatewayUniqueId *string `json:"gateway_unique_id,omitempty"`
	SupportUrl *string `json:"support_url,omitempty"`
	Onboarding *bool `json:"onboarding,omitempty"`
	Exclude []PolicyExclude `json:"exclude,omitempty"`
	Include []PolicyExclude `json:"include,omitempty"`
	FallbackDomains []FallbackDomain `json:"fallback_domains,omitempty"`
	SwitchLocked *bool `json:"switch_locked,omitempty"`
	AutoConnect *int32 `json:"auto_connect,omitempty"`
	ManagedMode *bool `json:"managed_mode,omitempty"`
	AllowModeSwitch *bool `json:"allow_mode_switch,omitempty"`
	AuthClientId *string `json:"auth_client_id,omitempty"`
	AuthClientSecret *string `json:"auth_client_secret,omitempty"`
	AllowedToLeave *bool `json:"allowed_to_leave,omitempty"`
	OverrideDohEndpoint *string `json:"override_doh_endpoint,omitempty"`
	OverrideWarpEndpoint *string `json:"override_warp_endpoint,omitempty"`
	OverrideApiEndpoint *string `json:"override_api_endpoint,omitempty"`
	UniqueClientId *string `json:"unique_client_id,omitempty"`
	TunnelProtocol *string `json:"tunnel_protocol,omitempty"`
	PolicyId *string `json:"policy_id,omitempty"`
	PostQuantum *PostQuantumSupport `json:"post_quantum,omitempty"`
	AlwaysExclude []PolicyIP `json:"always_exclude,omitempty"`
	AlwaysInclude []PolicyIP `json:"always_include,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Policy Policy

// NewPolicy instantiates a new Policy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicy() *Policy {
	this := Policy{}
	return &this
}

// NewPolicyWithDefaults instantiates a new Policy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyWithDefaults() *Policy {
	this := Policy{}
	return &this
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *Policy) GetOrganization() string {
	if o == nil || IsNil(o.Organization) {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetOrganizationOk() (*string, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *Policy) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *Policy) SetOrganization(v string) {
	o.Organization = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *Policy) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *Policy) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *Policy) SetEnable(v bool) {
	o.Enable = &v
}

// GetServiceMode returns the ServiceMode field value if set, zero value otherwise.
func (o *Policy) GetServiceMode() AppMode {
	if o == nil || IsNil(o.ServiceMode) {
		var ret AppMode
		return ret
	}
	return *o.ServiceMode
}

// GetServiceModeOk returns a tuple with the ServiceMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetServiceModeOk() (*AppMode, bool) {
	if o == nil || IsNil(o.ServiceMode) {
		return nil, false
	}
	return o.ServiceMode, true
}

// HasServiceMode returns a boolean if a field has been set.
func (o *Policy) HasServiceMode() bool {
	if o != nil && !IsNil(o.ServiceMode) {
		return true
	}

	return false
}

// SetServiceMode gets a reference to the given AppMode and assigns it to the ServiceMode field.
func (o *Policy) SetServiceMode(v AppMode) {
	o.ServiceMode = &v
}

// GetServiceModeV2 returns the ServiceModeV2 field value if set, zero value otherwise.
func (o *Policy) GetServiceModeV2() ServiceMode {
	if o == nil || IsNil(o.ServiceModeV2) {
		var ret ServiceMode
		return ret
	}
	return *o.ServiceModeV2
}

// GetServiceModeV2Ok returns a tuple with the ServiceModeV2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetServiceModeV2Ok() (*ServiceMode, bool) {
	if o == nil || IsNil(o.ServiceModeV2) {
		return nil, false
	}
	return o.ServiceModeV2, true
}

// HasServiceModeV2 returns a boolean if a field has been set.
func (o *Policy) HasServiceModeV2() bool {
	if o != nil && !IsNil(o.ServiceModeV2) {
		return true
	}

	return false
}

// SetServiceModeV2 gets a reference to the given ServiceMode and assigns it to the ServiceModeV2 field.
func (o *Policy) SetServiceModeV2(v ServiceMode) {
	o.ServiceModeV2 = &v
}

// GetGatewayUniqueId returns the GatewayUniqueId field value if set, zero value otherwise.
func (o *Policy) GetGatewayUniqueId() string {
	if o == nil || IsNil(o.GatewayUniqueId) {
		var ret string
		return ret
	}
	return *o.GatewayUniqueId
}

// GetGatewayUniqueIdOk returns a tuple with the GatewayUniqueId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetGatewayUniqueIdOk() (*string, bool) {
	if o == nil || IsNil(o.GatewayUniqueId) {
		return nil, false
	}
	return o.GatewayUniqueId, true
}

// HasGatewayUniqueId returns a boolean if a field has been set.
func (o *Policy) HasGatewayUniqueId() bool {
	if o != nil && !IsNil(o.GatewayUniqueId) {
		return true
	}

	return false
}

// SetGatewayUniqueId gets a reference to the given string and assigns it to the GatewayUniqueId field.
func (o *Policy) SetGatewayUniqueId(v string) {
	o.GatewayUniqueId = &v
}

// GetSupportUrl returns the SupportUrl field value if set, zero value otherwise.
func (o *Policy) GetSupportUrl() string {
	if o == nil || IsNil(o.SupportUrl) {
		var ret string
		return ret
	}
	return *o.SupportUrl
}

// GetSupportUrlOk returns a tuple with the SupportUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetSupportUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SupportUrl) {
		return nil, false
	}
	return o.SupportUrl, true
}

// HasSupportUrl returns a boolean if a field has been set.
func (o *Policy) HasSupportUrl() bool {
	if o != nil && !IsNil(o.SupportUrl) {
		return true
	}

	return false
}

// SetSupportUrl gets a reference to the given string and assigns it to the SupportUrl field.
func (o *Policy) SetSupportUrl(v string) {
	o.SupportUrl = &v
}

// GetOnboarding returns the Onboarding field value if set, zero value otherwise.
func (o *Policy) GetOnboarding() bool {
	if o == nil || IsNil(o.Onboarding) {
		var ret bool
		return ret
	}
	return *o.Onboarding
}

// GetOnboardingOk returns a tuple with the Onboarding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetOnboardingOk() (*bool, bool) {
	if o == nil || IsNil(o.Onboarding) {
		return nil, false
	}
	return o.Onboarding, true
}

// HasOnboarding returns a boolean if a field has been set.
func (o *Policy) HasOnboarding() bool {
	if o != nil && !IsNil(o.Onboarding) {
		return true
	}

	return false
}

// SetOnboarding gets a reference to the given bool and assigns it to the Onboarding field.
func (o *Policy) SetOnboarding(v bool) {
	o.Onboarding = &v
}

// GetExclude returns the Exclude field value if set, zero value otherwise.
func (o *Policy) GetExclude() []PolicyExclude {
	if o == nil || IsNil(o.Exclude) {
		var ret []PolicyExclude
		return ret
	}
	return o.Exclude
}

// GetExcludeOk returns a tuple with the Exclude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetExcludeOk() ([]PolicyExclude, bool) {
	if o == nil || IsNil(o.Exclude) {
		return nil, false
	}
	return o.Exclude, true
}

// HasExclude returns a boolean if a field has been set.
func (o *Policy) HasExclude() bool {
	if o != nil && !IsNil(o.Exclude) {
		return true
	}

	return false
}

// SetExclude gets a reference to the given []PolicyExclude and assigns it to the Exclude field.
func (o *Policy) SetExclude(v []PolicyExclude) {
	o.Exclude = v
}

// GetInclude returns the Include field value if set, zero value otherwise.
func (o *Policy) GetInclude() []PolicyExclude {
	if o == nil || IsNil(o.Include) {
		var ret []PolicyExclude
		return ret
	}
	return o.Include
}

// GetIncludeOk returns a tuple with the Include field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetIncludeOk() ([]PolicyExclude, bool) {
	if o == nil || IsNil(o.Include) {
		return nil, false
	}
	return o.Include, true
}

// HasInclude returns a boolean if a field has been set.
func (o *Policy) HasInclude() bool {
	if o != nil && !IsNil(o.Include) {
		return true
	}

	return false
}

// SetInclude gets a reference to the given []PolicyExclude and assigns it to the Include field.
func (o *Policy) SetInclude(v []PolicyExclude) {
	o.Include = v
}

// GetFallbackDomains returns the FallbackDomains field value if set, zero value otherwise.
func (o *Policy) GetFallbackDomains() []FallbackDomain {
	if o == nil || IsNil(o.FallbackDomains) {
		var ret []FallbackDomain
		return ret
	}
	return o.FallbackDomains
}

// GetFallbackDomainsOk returns a tuple with the FallbackDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetFallbackDomainsOk() ([]FallbackDomain, bool) {
	if o == nil || IsNil(o.FallbackDomains) {
		return nil, false
	}
	return o.FallbackDomains, true
}

// HasFallbackDomains returns a boolean if a field has been set.
func (o *Policy) HasFallbackDomains() bool {
	if o != nil && !IsNil(o.FallbackDomains) {
		return true
	}

	return false
}

// SetFallbackDomains gets a reference to the given []FallbackDomain and assigns it to the FallbackDomains field.
func (o *Policy) SetFallbackDomains(v []FallbackDomain) {
	o.FallbackDomains = v
}

// GetSwitchLocked returns the SwitchLocked field value if set, zero value otherwise.
func (o *Policy) GetSwitchLocked() bool {
	if o == nil || IsNil(o.SwitchLocked) {
		var ret bool
		return ret
	}
	return *o.SwitchLocked
}

// GetSwitchLockedOk returns a tuple with the SwitchLocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetSwitchLockedOk() (*bool, bool) {
	if o == nil || IsNil(o.SwitchLocked) {
		return nil, false
	}
	return o.SwitchLocked, true
}

// HasSwitchLocked returns a boolean if a field has been set.
func (o *Policy) HasSwitchLocked() bool {
	if o != nil && !IsNil(o.SwitchLocked) {
		return true
	}

	return false
}

// SetSwitchLocked gets a reference to the given bool and assigns it to the SwitchLocked field.
func (o *Policy) SetSwitchLocked(v bool) {
	o.SwitchLocked = &v
}

// GetAutoConnect returns the AutoConnect field value if set, zero value otherwise.
func (o *Policy) GetAutoConnect() int32 {
	if o == nil || IsNil(o.AutoConnect) {
		var ret int32
		return ret
	}
	return *o.AutoConnect
}

// GetAutoConnectOk returns a tuple with the AutoConnect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetAutoConnectOk() (*int32, bool) {
	if o == nil || IsNil(o.AutoConnect) {
		return nil, false
	}
	return o.AutoConnect, true
}

// HasAutoConnect returns a boolean if a field has been set.
func (o *Policy) HasAutoConnect() bool {
	if o != nil && !IsNil(o.AutoConnect) {
		return true
	}

	return false
}

// SetAutoConnect gets a reference to the given int32 and assigns it to the AutoConnect field.
func (o *Policy) SetAutoConnect(v int32) {
	o.AutoConnect = &v
}

// GetManagedMode returns the ManagedMode field value if set, zero value otherwise.
func (o *Policy) GetManagedMode() bool {
	if o == nil || IsNil(o.ManagedMode) {
		var ret bool
		return ret
	}
	return *o.ManagedMode
}

// GetManagedModeOk returns a tuple with the ManagedMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetManagedModeOk() (*bool, bool) {
	if o == nil || IsNil(o.ManagedMode) {
		return nil, false
	}
	return o.ManagedMode, true
}

// HasManagedMode returns a boolean if a field has been set.
func (o *Policy) HasManagedMode() bool {
	if o != nil && !IsNil(o.ManagedMode) {
		return true
	}

	return false
}

// SetManagedMode gets a reference to the given bool and assigns it to the ManagedMode field.
func (o *Policy) SetManagedMode(v bool) {
	o.ManagedMode = &v
}

// GetAllowModeSwitch returns the AllowModeSwitch field value if set, zero value otherwise.
func (o *Policy) GetAllowModeSwitch() bool {
	if o == nil || IsNil(o.AllowModeSwitch) {
		var ret bool
		return ret
	}
	return *o.AllowModeSwitch
}

// GetAllowModeSwitchOk returns a tuple with the AllowModeSwitch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetAllowModeSwitchOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowModeSwitch) {
		return nil, false
	}
	return o.AllowModeSwitch, true
}

// HasAllowModeSwitch returns a boolean if a field has been set.
func (o *Policy) HasAllowModeSwitch() bool {
	if o != nil && !IsNil(o.AllowModeSwitch) {
		return true
	}

	return false
}

// SetAllowModeSwitch gets a reference to the given bool and assigns it to the AllowModeSwitch field.
func (o *Policy) SetAllowModeSwitch(v bool) {
	o.AllowModeSwitch = &v
}

// GetAuthClientId returns the AuthClientId field value if set, zero value otherwise.
func (o *Policy) GetAuthClientId() string {
	if o == nil || IsNil(o.AuthClientId) {
		var ret string
		return ret
	}
	return *o.AuthClientId
}

// GetAuthClientIdOk returns a tuple with the AuthClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetAuthClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.AuthClientId) {
		return nil, false
	}
	return o.AuthClientId, true
}

// HasAuthClientId returns a boolean if a field has been set.
func (o *Policy) HasAuthClientId() bool {
	if o != nil && !IsNil(o.AuthClientId) {
		return true
	}

	return false
}

// SetAuthClientId gets a reference to the given string and assigns it to the AuthClientId field.
func (o *Policy) SetAuthClientId(v string) {
	o.AuthClientId = &v
}

// GetAuthClientSecret returns the AuthClientSecret field value if set, zero value otherwise.
func (o *Policy) GetAuthClientSecret() string {
	if o == nil || IsNil(o.AuthClientSecret) {
		var ret string
		return ret
	}
	return *o.AuthClientSecret
}

// GetAuthClientSecretOk returns a tuple with the AuthClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetAuthClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.AuthClientSecret) {
		return nil, false
	}
	return o.AuthClientSecret, true
}

// HasAuthClientSecret returns a boolean if a field has been set.
func (o *Policy) HasAuthClientSecret() bool {
	if o != nil && !IsNil(o.AuthClientSecret) {
		return true
	}

	return false
}

// SetAuthClientSecret gets a reference to the given string and assigns it to the AuthClientSecret field.
func (o *Policy) SetAuthClientSecret(v string) {
	o.AuthClientSecret = &v
}

// GetAllowedToLeave returns the AllowedToLeave field value if set, zero value otherwise.
func (o *Policy) GetAllowedToLeave() bool {
	if o == nil || IsNil(o.AllowedToLeave) {
		var ret bool
		return ret
	}
	return *o.AllowedToLeave
}

// GetAllowedToLeaveOk returns a tuple with the AllowedToLeave field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetAllowedToLeaveOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowedToLeave) {
		return nil, false
	}
	return o.AllowedToLeave, true
}

// HasAllowedToLeave returns a boolean if a field has been set.
func (o *Policy) HasAllowedToLeave() bool {
	if o != nil && !IsNil(o.AllowedToLeave) {
		return true
	}

	return false
}

// SetAllowedToLeave gets a reference to the given bool and assigns it to the AllowedToLeave field.
func (o *Policy) SetAllowedToLeave(v bool) {
	o.AllowedToLeave = &v
}

// GetOverrideDohEndpoint returns the OverrideDohEndpoint field value if set, zero value otherwise.
func (o *Policy) GetOverrideDohEndpoint() string {
	if o == nil || IsNil(o.OverrideDohEndpoint) {
		var ret string
		return ret
	}
	return *o.OverrideDohEndpoint
}

// GetOverrideDohEndpointOk returns a tuple with the OverrideDohEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetOverrideDohEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.OverrideDohEndpoint) {
		return nil, false
	}
	return o.OverrideDohEndpoint, true
}

// HasOverrideDohEndpoint returns a boolean if a field has been set.
func (o *Policy) HasOverrideDohEndpoint() bool {
	if o != nil && !IsNil(o.OverrideDohEndpoint) {
		return true
	}

	return false
}

// SetOverrideDohEndpoint gets a reference to the given string and assigns it to the OverrideDohEndpoint field.
func (o *Policy) SetOverrideDohEndpoint(v string) {
	o.OverrideDohEndpoint = &v
}

// GetOverrideWarpEndpoint returns the OverrideWarpEndpoint field value if set, zero value otherwise.
func (o *Policy) GetOverrideWarpEndpoint() string {
	if o == nil || IsNil(o.OverrideWarpEndpoint) {
		var ret string
		return ret
	}
	return *o.OverrideWarpEndpoint
}

// GetOverrideWarpEndpointOk returns a tuple with the OverrideWarpEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetOverrideWarpEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.OverrideWarpEndpoint) {
		return nil, false
	}
	return o.OverrideWarpEndpoint, true
}

// HasOverrideWarpEndpoint returns a boolean if a field has been set.
func (o *Policy) HasOverrideWarpEndpoint() bool {
	if o != nil && !IsNil(o.OverrideWarpEndpoint) {
		return true
	}

	return false
}

// SetOverrideWarpEndpoint gets a reference to the given string and assigns it to the OverrideWarpEndpoint field.
func (o *Policy) SetOverrideWarpEndpoint(v string) {
	o.OverrideWarpEndpoint = &v
}

// GetOverrideApiEndpoint returns the OverrideApiEndpoint field value if set, zero value otherwise.
func (o *Policy) GetOverrideApiEndpoint() string {
	if o == nil || IsNil(o.OverrideApiEndpoint) {
		var ret string
		return ret
	}
	return *o.OverrideApiEndpoint
}

// GetOverrideApiEndpointOk returns a tuple with the OverrideApiEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetOverrideApiEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.OverrideApiEndpoint) {
		return nil, false
	}
	return o.OverrideApiEndpoint, true
}

// HasOverrideApiEndpoint returns a boolean if a field has been set.
func (o *Policy) HasOverrideApiEndpoint() bool {
	if o != nil && !IsNil(o.OverrideApiEndpoint) {
		return true
	}

	return false
}

// SetOverrideApiEndpoint gets a reference to the given string and assigns it to the OverrideApiEndpoint field.
func (o *Policy) SetOverrideApiEndpoint(v string) {
	o.OverrideApiEndpoint = &v
}

// GetUniqueClientId returns the UniqueClientId field value if set, zero value otherwise.
func (o *Policy) GetUniqueClientId() string {
	if o == nil || IsNil(o.UniqueClientId) {
		var ret string
		return ret
	}
	return *o.UniqueClientId
}

// GetUniqueClientIdOk returns a tuple with the UniqueClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetUniqueClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.UniqueClientId) {
		return nil, false
	}
	return o.UniqueClientId, true
}

// HasUniqueClientId returns a boolean if a field has been set.
func (o *Policy) HasUniqueClientId() bool {
	if o != nil && !IsNil(o.UniqueClientId) {
		return true
	}

	return false
}

// SetUniqueClientId gets a reference to the given string and assigns it to the UniqueClientId field.
func (o *Policy) SetUniqueClientId(v string) {
	o.UniqueClientId = &v
}

// GetTunnelProtocol returns the TunnelProtocol field value if set, zero value otherwise.
func (o *Policy) GetTunnelProtocol() string {
	if o == nil || IsNil(o.TunnelProtocol) {
		var ret string
		return ret
	}
	return *o.TunnelProtocol
}

// GetTunnelProtocolOk returns a tuple with the TunnelProtocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetTunnelProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.TunnelProtocol) {
		return nil, false
	}
	return o.TunnelProtocol, true
}

// HasTunnelProtocol returns a boolean if a field has been set.
func (o *Policy) HasTunnelProtocol() bool {
	if o != nil && !IsNil(o.TunnelProtocol) {
		return true
	}

	return false
}

// SetTunnelProtocol gets a reference to the given string and assigns it to the TunnelProtocol field.
func (o *Policy) SetTunnelProtocol(v string) {
	o.TunnelProtocol = &v
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise.
func (o *Policy) GetPolicyId() string {
	if o == nil || IsNil(o.PolicyId) {
		var ret string
		return ret
	}
	return *o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetPolicyIdOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyId) {
		return nil, false
	}
	return o.PolicyId, true
}

// HasPolicyId returns a boolean if a field has been set.
func (o *Policy) HasPolicyId() bool {
	if o != nil && !IsNil(o.PolicyId) {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given string and assigns it to the PolicyId field.
func (o *Policy) SetPolicyId(v string) {
	o.PolicyId = &v
}

// GetPostQuantum returns the PostQuantum field value if set, zero value otherwise.
func (o *Policy) GetPostQuantum() PostQuantumSupport {
	if o == nil || IsNil(o.PostQuantum) {
		var ret PostQuantumSupport
		return ret
	}
	return *o.PostQuantum
}

// GetPostQuantumOk returns a tuple with the PostQuantum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetPostQuantumOk() (*PostQuantumSupport, bool) {
	if o == nil || IsNil(o.PostQuantum) {
		return nil, false
	}
	return o.PostQuantum, true
}

// HasPostQuantum returns a boolean if a field has been set.
func (o *Policy) HasPostQuantum() bool {
	if o != nil && !IsNil(o.PostQuantum) {
		return true
	}

	return false
}

// SetPostQuantum gets a reference to the given PostQuantumSupport and assigns it to the PostQuantum field.
func (o *Policy) SetPostQuantum(v PostQuantumSupport) {
	o.PostQuantum = &v
}

// GetAlwaysExclude returns the AlwaysExclude field value if set, zero value otherwise.
func (o *Policy) GetAlwaysExclude() []PolicyIP {
	if o == nil || IsNil(o.AlwaysExclude) {
		var ret []PolicyIP
		return ret
	}
	return o.AlwaysExclude
}

// GetAlwaysExcludeOk returns a tuple with the AlwaysExclude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetAlwaysExcludeOk() ([]PolicyIP, bool) {
	if o == nil || IsNil(o.AlwaysExclude) {
		return nil, false
	}
	return o.AlwaysExclude, true
}

// HasAlwaysExclude returns a boolean if a field has been set.
func (o *Policy) HasAlwaysExclude() bool {
	if o != nil && !IsNil(o.AlwaysExclude) {
		return true
	}

	return false
}

// SetAlwaysExclude gets a reference to the given []PolicyIP and assigns it to the AlwaysExclude field.
func (o *Policy) SetAlwaysExclude(v []PolicyIP) {
	o.AlwaysExclude = v
}

// GetAlwaysInclude returns the AlwaysInclude field value if set, zero value otherwise.
func (o *Policy) GetAlwaysInclude() []PolicyIP {
	if o == nil || IsNil(o.AlwaysInclude) {
		var ret []PolicyIP
		return ret
	}
	return o.AlwaysInclude
}

// GetAlwaysIncludeOk returns a tuple with the AlwaysInclude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Policy) GetAlwaysIncludeOk() ([]PolicyIP, bool) {
	if o == nil || IsNil(o.AlwaysInclude) {
		return nil, false
	}
	return o.AlwaysInclude, true
}

// HasAlwaysInclude returns a boolean if a field has been set.
func (o *Policy) HasAlwaysInclude() bool {
	if o != nil && !IsNil(o.AlwaysInclude) {
		return true
	}

	return false
}

// SetAlwaysInclude gets a reference to the given []PolicyIP and assigns it to the AlwaysInclude field.
func (o *Policy) SetAlwaysInclude(v []PolicyIP) {
	o.AlwaysInclude = v
}

func (o Policy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Policy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.ServiceMode) {
		toSerialize["service_mode"] = o.ServiceMode
	}
	if !IsNil(o.ServiceModeV2) {
		toSerialize["service_mode_v2"] = o.ServiceModeV2
	}
	if !IsNil(o.GatewayUniqueId) {
		toSerialize["gateway_unique_id"] = o.GatewayUniqueId
	}
	if !IsNil(o.SupportUrl) {
		toSerialize["support_url"] = o.SupportUrl
	}
	if !IsNil(o.Onboarding) {
		toSerialize["onboarding"] = o.Onboarding
	}
	if !IsNil(o.Exclude) {
		toSerialize["exclude"] = o.Exclude
	}
	if !IsNil(o.Include) {
		toSerialize["include"] = o.Include
	}
	if !IsNil(o.FallbackDomains) {
		toSerialize["fallback_domains"] = o.FallbackDomains
	}
	if !IsNil(o.SwitchLocked) {
		toSerialize["switch_locked"] = o.SwitchLocked
	}
	if !IsNil(o.AutoConnect) {
		toSerialize["auto_connect"] = o.AutoConnect
	}
	if !IsNil(o.ManagedMode) {
		toSerialize["managed_mode"] = o.ManagedMode
	}
	if !IsNil(o.AllowModeSwitch) {
		toSerialize["allow_mode_switch"] = o.AllowModeSwitch
	}
	if !IsNil(o.AuthClientId) {
		toSerialize["auth_client_id"] = o.AuthClientId
	}
	if !IsNil(o.AuthClientSecret) {
		toSerialize["auth_client_secret"] = o.AuthClientSecret
	}
	if !IsNil(o.AllowedToLeave) {
		toSerialize["allowed_to_leave"] = o.AllowedToLeave
	}
	if !IsNil(o.OverrideDohEndpoint) {
		toSerialize["override_doh_endpoint"] = o.OverrideDohEndpoint
	}
	if !IsNil(o.OverrideWarpEndpoint) {
		toSerialize["override_warp_endpoint"] = o.OverrideWarpEndpoint
	}
	if !IsNil(o.OverrideApiEndpoint) {
		toSerialize["override_api_endpoint"] = o.OverrideApiEndpoint
	}
	if !IsNil(o.UniqueClientId) {
		toSerialize["unique_client_id"] = o.UniqueClientId
	}
	if !IsNil(o.TunnelProtocol) {
		toSerialize["tunnel_protocol"] = o.TunnelProtocol
	}
	if !IsNil(o.PolicyId) {
		toSerialize["policy_id"] = o.PolicyId
	}
	if !IsNil(o.PostQuantum) {
		toSerialize["post_quantum"] = o.PostQuantum
	}
	if !IsNil(o.AlwaysExclude) {
		toSerialize["always_exclude"] = o.AlwaysExclude
	}
	if !IsNil(o.AlwaysInclude) {
		toSerialize["always_include"] = o.AlwaysInclude
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Policy) UnmarshalJSON(data []byte) (err error) {
	varPolicy := _Policy{}

	err = json.Unmarshal(data, &varPolicy)

	if err != nil {
		return err
	}

	*o = Policy(varPolicy)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "organization")
		delete(additionalProperties, "enable")
		delete(additionalProperties, "service_mode")
		delete(additionalProperties, "service_mode_v2")
		delete(additionalProperties, "gateway_unique_id")
		delete(additionalProperties, "support_url")
		delete(additionalProperties, "onboarding")
		delete(additionalProperties, "exclude")
		delete(additionalProperties, "include")
		delete(additionalProperties, "fallback_domains")
		delete(additionalProperties, "switch_locked")
		delete(additionalProperties, "auto_connect")
		delete(additionalProperties, "managed_mode")
		delete(additionalProperties, "allow_mode_switch")
		delete(additionalProperties, "auth_client_id")
		delete(additionalProperties, "auth_client_secret")
		delete(additionalProperties, "allowed_to_leave")
		delete(additionalProperties, "override_doh_endpoint")
		delete(additionalProperties, "override_warp_endpoint")
		delete(additionalProperties, "override_api_endpoint")
		delete(additionalProperties, "unique_client_id")
		delete(additionalProperties, "tunnel_protocol")
		delete(additionalProperties, "policy_id")
		delete(additionalProperties, "post_quantum")
		delete(additionalProperties, "always_exclude")
		delete(additionalProperties, "always_include")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolicy struct {
	value *Policy
	isSet bool
}

func (v NullablePolicy) Get() *Policy {
	return v.value
}

func (v *NullablePolicy) Set(val *Policy) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicy) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicy(val *Policy) *NullablePolicy {
	return &NullablePolicy{value: val, isSet: true}
}

func (v NullablePolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


