/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FallbackDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FallbackDomain{}

// FallbackDomain struct for FallbackDomain
type FallbackDomain struct {
	Suffix *string `json:"suffix,omitempty"`
	Description *string `json:"description,omitempty"`
	DnsServer []string `json:"dns_server,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FallbackDomain FallbackDomain

// NewFallbackDomain instantiates a new FallbackDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFallbackDomain() *FallbackDomain {
	this := FallbackDomain{}
	return &this
}

// NewFallbackDomainWithDefaults instantiates a new FallbackDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFallbackDomainWithDefaults() *FallbackDomain {
	this := FallbackDomain{}
	return &this
}

// GetSuffix returns the Suffix field value if set, zero value otherwise.
func (o *FallbackDomain) GetSuffix() string {
	if o == nil || IsNil(o.Suffix) {
		var ret string
		return ret
	}
	return *o.Suffix
}

// GetSuffixOk returns a tuple with the Suffix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FallbackDomain) GetSuffixOk() (*string, bool) {
	if o == nil || IsNil(o.Suffix) {
		return nil, false
	}
	return o.Suffix, true
}

// HasSuffix returns a boolean if a field has been set.
func (o *FallbackDomain) HasSuffix() bool {
	if o != nil && !IsNil(o.Suffix) {
		return true
	}

	return false
}

// SetSuffix gets a reference to the given string and assigns it to the Suffix field.
func (o *FallbackDomain) SetSuffix(v string) {
	o.Suffix = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FallbackDomain) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FallbackDomain) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FallbackDomain) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FallbackDomain) SetDescription(v string) {
	o.Description = &v
}

// GetDnsServer returns the DnsServer field value if set, zero value otherwise.
func (o *FallbackDomain) GetDnsServer() []string {
	if o == nil || IsNil(o.DnsServer) {
		var ret []string
		return ret
	}
	return o.DnsServer
}

// GetDnsServerOk returns a tuple with the DnsServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FallbackDomain) GetDnsServerOk() ([]string, bool) {
	if o == nil || IsNil(o.DnsServer) {
		return nil, false
	}
	return o.DnsServer, true
}

// HasDnsServer returns a boolean if a field has been set.
func (o *FallbackDomain) HasDnsServer() bool {
	if o != nil && !IsNil(o.DnsServer) {
		return true
	}

	return false
}

// SetDnsServer gets a reference to the given []string and assigns it to the DnsServer field.
func (o *FallbackDomain) SetDnsServer(v []string) {
	o.DnsServer = v
}

func (o FallbackDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FallbackDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Suffix) {
		toSerialize["suffix"] = o.Suffix
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DnsServer) {
		toSerialize["dns_server"] = o.DnsServer
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FallbackDomain) UnmarshalJSON(data []byte) (err error) {
	varFallbackDomain := _FallbackDomain{}

	err = json.Unmarshal(data, &varFallbackDomain)

	if err != nil {
		return err
	}

	*o = FallbackDomain(varFallbackDomain)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "suffix")
		delete(additionalProperties, "description")
		delete(additionalProperties, "dns_server")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFallbackDomain struct {
	value *FallbackDomain
	isSet bool
}

func (v NullableFallbackDomain) Get() *FallbackDomain {
	return v.value
}

func (v *NullableFallbackDomain) Set(val *FallbackDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableFallbackDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableFallbackDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFallbackDomain(val *FallbackDomain) *NullableFallbackDomain {
	return &NullableFallbackDomain{value: val, isSet: true}
}

func (v NullableFallbackDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFallbackDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


