/*
untitled API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 536
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateSourceDevice200ResponseAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSourceDevice200ResponseAccount{}

// UpdateSourceDevice200ResponseAccount struct for UpdateSourceDevice200ResponseAccount
type UpdateSourceDevice200ResponseAccount struct {
	AccountType string `json:"account_type"`
	Created string `json:"created"`
	Id string `json:"id"`
	License string `json:"license"`
	PremiumData float32 `json:"premium_data"`
	Quota float32 `json:"quota"`
	ReferralCount float32 `json:"referral_count"`
	ReferralRenewalCountdown float32 `json:"referral_renewal_countdown"`
	Role string `json:"role"`
	Updated string `json:"updated"`
	WarpPlus bool `json:"warp_plus"`
	AdditionalProperties map[string]interface{}
}

type _UpdateSourceDevice200ResponseAccount UpdateSourceDevice200ResponseAccount

// NewUpdateSourceDevice200ResponseAccount instantiates a new UpdateSourceDevice200ResponseAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSourceDevice200ResponseAccount(accountType string, created string, id string, license string, premiumData float32, quota float32, referralCount float32, referralRenewalCountdown float32, role string, updated string, warpPlus bool) *UpdateSourceDevice200ResponseAccount {
	this := UpdateSourceDevice200ResponseAccount{}
	this.AccountType = accountType
	this.Created = created
	this.Id = id
	this.License = license
	this.PremiumData = premiumData
	this.Quota = quota
	this.ReferralCount = referralCount
	this.ReferralRenewalCountdown = referralRenewalCountdown
	this.Role = role
	this.Updated = updated
	this.WarpPlus = warpPlus
	return &this
}

// NewUpdateSourceDevice200ResponseAccountWithDefaults instantiates a new UpdateSourceDevice200ResponseAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSourceDevice200ResponseAccountWithDefaults() *UpdateSourceDevice200ResponseAccount {
	this := UpdateSourceDevice200ResponseAccount{}
	return &this
}

// GetAccountType returns the AccountType field value
func (o *UpdateSourceDevice200ResponseAccount) GetAccountType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetAccountTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountType, true
}

// SetAccountType sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetAccountType(v string) {
	o.AccountType = v
}

// GetCreated returns the Created field value
func (o *UpdateSourceDevice200ResponseAccount) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetCreated(v string) {
	o.Created = v
}

// GetId returns the Id field value
func (o *UpdateSourceDevice200ResponseAccount) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetId(v string) {
	o.Id = v
}

// GetLicense returns the License field value
func (o *UpdateSourceDevice200ResponseAccount) GetLicense() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.License
}

// GetLicenseOk returns a tuple with the License field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetLicenseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.License, true
}

// SetLicense sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetLicense(v string) {
	o.License = v
}

// GetPremiumData returns the PremiumData field value
func (o *UpdateSourceDevice200ResponseAccount) GetPremiumData() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PremiumData
}

// GetPremiumDataOk returns a tuple with the PremiumData field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetPremiumDataOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PremiumData, true
}

// SetPremiumData sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetPremiumData(v float32) {
	o.PremiumData = v
}

// GetQuota returns the Quota field value
func (o *UpdateSourceDevice200ResponseAccount) GetQuota() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quota, true
}

// SetQuota sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetQuota(v float32) {
	o.Quota = v
}

// GetReferralCount returns the ReferralCount field value
func (o *UpdateSourceDevice200ResponseAccount) GetReferralCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ReferralCount
}

// GetReferralCountOk returns a tuple with the ReferralCount field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetReferralCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralCount, true
}

// SetReferralCount sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetReferralCount(v float32) {
	o.ReferralCount = v
}

// GetReferralRenewalCountdown returns the ReferralRenewalCountdown field value
func (o *UpdateSourceDevice200ResponseAccount) GetReferralRenewalCountdown() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ReferralRenewalCountdown
}

// GetReferralRenewalCountdownOk returns a tuple with the ReferralRenewalCountdown field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetReferralRenewalCountdownOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferralRenewalCountdown, true
}

// SetReferralRenewalCountdown sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetReferralRenewalCountdown(v float32) {
	o.ReferralRenewalCountdown = v
}

// GetRole returns the Role field value
func (o *UpdateSourceDevice200ResponseAccount) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetRole(v string) {
	o.Role = v
}

// GetUpdated returns the Updated field value
func (o *UpdateSourceDevice200ResponseAccount) GetUpdated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetUpdatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetUpdated(v string) {
	o.Updated = v
}

// GetWarpPlus returns the WarpPlus field value
func (o *UpdateSourceDevice200ResponseAccount) GetWarpPlus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.WarpPlus
}

// GetWarpPlusOk returns a tuple with the WarpPlus field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200ResponseAccount) GetWarpPlusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WarpPlus, true
}

// SetWarpPlus sets field value
func (o *UpdateSourceDevice200ResponseAccount) SetWarpPlus(v bool) {
	o.WarpPlus = v
}

func (o UpdateSourceDevice200ResponseAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSourceDevice200ResponseAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_type"] = o.AccountType
	toSerialize["created"] = o.Created
	toSerialize["id"] = o.Id
	toSerialize["license"] = o.License
	toSerialize["premium_data"] = o.PremiumData
	toSerialize["quota"] = o.Quota
	toSerialize["referral_count"] = o.ReferralCount
	toSerialize["referral_renewal_countdown"] = o.ReferralRenewalCountdown
	toSerialize["role"] = o.Role
	toSerialize["updated"] = o.Updated
	toSerialize["warp_plus"] = o.WarpPlus

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateSourceDevice200ResponseAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_type",
		"created",
		"id",
		"license",
		"premium_data",
		"quota",
		"referral_count",
		"referral_renewal_countdown",
		"role",
		"updated",
		"warp_plus",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSourceDevice200ResponseAccount := _UpdateSourceDevice200ResponseAccount{}

	err = json.Unmarshal(data, &varUpdateSourceDevice200ResponseAccount)

	if err != nil {
		return err
	}

	*o = UpdateSourceDevice200ResponseAccount(varUpdateSourceDevice200ResponseAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_type")
		delete(additionalProperties, "created")
		delete(additionalProperties, "id")
		delete(additionalProperties, "license")
		delete(additionalProperties, "premium_data")
		delete(additionalProperties, "quota")
		delete(additionalProperties, "referral_count")
		delete(additionalProperties, "referral_renewal_countdown")
		delete(additionalProperties, "role")
		delete(additionalProperties, "updated")
		delete(additionalProperties, "warp_plus")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateSourceDevice200ResponseAccount struct {
	value *UpdateSourceDevice200ResponseAccount
	isSet bool
}

func (v NullableUpdateSourceDevice200ResponseAccount) Get() *UpdateSourceDevice200ResponseAccount {
	return v.value
}

func (v *NullableUpdateSourceDevice200ResponseAccount) Set(val *UpdateSourceDevice200ResponseAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSourceDevice200ResponseAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSourceDevice200ResponseAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSourceDevice200ResponseAccount(val *UpdateSourceDevice200ResponseAccount) *NullableUpdateSourceDevice200ResponseAccount {
	return &NullableUpdateSourceDevice200ResponseAccount{value: val, isSet: true}
}

func (v NullableUpdateSourceDevice200ResponseAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSourceDevice200ResponseAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


