/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// AppMode the model 'AppMode'
type AppMode string

// List of AppMode
const (
	_1DOT1 AppMode = "1dot1"
	WARP AppMode = "warp"
	POSTURE_ONLY AppMode = "posture_only"
	WARP_TUNNEL_ONLY AppMode = "warp_tunnel_only"
	PROXY AppMode = "proxy"
)

// All allowed values of AppMode enum
var AllowedAppModeEnumValues = []AppMode{
	"1dot1",
	"warp",
	"posture_only",
	"warp_tunnel_only",
	"proxy",
}

func (v *AppMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AppMode(value)
	for _, existing := range AllowedAppModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AppMode", value)
}

// NewAppModeFromValue returns a pointer to a valid AppMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAppModeFromValue(v string) (*AppMode, error) {
	ev := AppMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AppMode: valid values are %v", v, AllowedAppModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AppMode) IsValid() bool {
	for _, existing := range AllowedAppModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AppMode value
func (v AppMode) Ptr() *AppMode {
	return &v
}

type NullableAppMode struct {
	value *AppMode
	isSet bool
}

func (v NullableAppMode) Get() *AppMode {
	return v.value
}

func (v *NullableAppMode) Set(val *AppMode) {
	v.value = val
	v.isSet = true
}

func (v NullableAppMode) IsSet() bool {
	return v.isSet
}

func (v *NullableAppMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppMode(val *AppMode) *NullableAppMode {
	return &NullableAppMode{value: val, isSet: true}
}

func (v NullableAppMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

