/*
Cloudflare WARP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 536
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigServices type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigServices{}

// ConfigServices struct for ConfigServices
type ConfigServices struct {
	HttpProxy string `json:"http_proxy"`
	AdditionalProperties map[string]interface{}
}

type _ConfigServices ConfigServices

// NewConfigServices instantiates a new ConfigServices object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigServices(httpProxy string) *ConfigServices {
	this := ConfigServices{}
	this.HttpProxy = httpProxy
	return &this
}

// NewConfigServicesWithDefaults instantiates a new ConfigServices object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigServicesWithDefaults() *ConfigServices {
	this := ConfigServices{}
	return &this
}

// GetHttpProxy returns the HttpProxy field value
func (o *ConfigServices) GetHttpProxy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HttpProxy
}

// GetHttpProxyOk returns a tuple with the HttpProxy field value
// and a boolean to check if the value has been set.
func (o *ConfigServices) GetHttpProxyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HttpProxy, true
}

// SetHttpProxy sets field value
func (o *ConfigServices) SetHttpProxy(v string) {
	o.HttpProxy = v
}

func (o ConfigServices) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigServices) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["http_proxy"] = o.HttpProxy

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigServices) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"http_proxy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigServices := _ConfigServices{}

	err = json.Unmarshal(data, &varConfigServices)

	if err != nil {
		return err
	}

	*o = ConfigServices(varConfigServices)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "http_proxy")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigServices struct {
	value *ConfigServices
	isSet bool
}

func (v NullableConfigServices) Get() *ConfigServices {
	return v.value
}

func (v *NullableConfigServices) Set(val *ConfigServices) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigServices) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigServices) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigServices(val *ConfigServices) *NullableConfigServices {
	return &NullableConfigServices{value: val, isSet: true}
}

func (v NullableConfigServices) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigServices) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


