/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the RegisterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterRequest{}

// RegisterRequest struct for RegisterRequest
type RegisterRequest struct {
	FcmToken string `json:"fcm_token"`
	InstallId string `json:"install_id"`
	Key string `json:"key"`
	Locale string `json:"locale"`
	Model *string `json:"model,omitempty"`
	Referrer *string `json:"referrer,omitempty"`
	Tos *string `json:"tos,omitempty"`
	Expired *string `json:"expired,omitempty"`
	SerialNumber string `json:"serial_number"`
	OsVersion *string `json:"os_version,omitempty"`
	KeyType *string `json:"key_type,omitempty"`
	TunnelType *string `json:"tunnel_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RegisterRequest RegisterRequest

// NewRegisterRequest instantiates a new RegisterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterRequest(fcmToken string, installId string, key string, locale string, serialNumber string) *RegisterRequest {
	this := RegisterRequest{}
	this.FcmToken = fcmToken
	this.InstallId = installId
	this.Key = key
	this.Locale = locale
	this.SerialNumber = serialNumber
	return &this
}

// NewRegisterRequestWithDefaults instantiates a new RegisterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterRequestWithDefaults() *RegisterRequest {
	this := RegisterRequest{}
	return &this
}

// GetFcmToken returns the FcmToken field value
func (o *RegisterRequest) GetFcmToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FcmToken
}

// GetFcmTokenOk returns a tuple with the FcmToken field value
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetFcmTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FcmToken, true
}

// SetFcmToken sets field value
func (o *RegisterRequest) SetFcmToken(v string) {
	o.FcmToken = v
}

// GetInstallId returns the InstallId field value
func (o *RegisterRequest) GetInstallId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstallId
}

// GetInstallIdOk returns a tuple with the InstallId field value
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetInstallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstallId, true
}

// SetInstallId sets field value
func (o *RegisterRequest) SetInstallId(v string) {
	o.InstallId = v
}

// GetKey returns the Key field value
func (o *RegisterRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *RegisterRequest) SetKey(v string) {
	o.Key = v
}

// GetLocale returns the Locale field value
func (o *RegisterRequest) GetLocale() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
func (o *RegisterRequest) SetLocale(v string) {
	o.Locale = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *RegisterRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *RegisterRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *RegisterRequest) SetModel(v string) {
	o.Model = &v
}

// GetReferrer returns the Referrer field value if set, zero value otherwise.
func (o *RegisterRequest) GetReferrer() string {
	if o == nil || IsNil(o.Referrer) {
		var ret string
		return ret
	}
	return *o.Referrer
}

// GetReferrerOk returns a tuple with the Referrer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetReferrerOk() (*string, bool) {
	if o == nil || IsNil(o.Referrer) {
		return nil, false
	}
	return o.Referrer, true
}

// HasReferrer returns a boolean if a field has been set.
func (o *RegisterRequest) HasReferrer() bool {
	if o != nil && !IsNil(o.Referrer) {
		return true
	}

	return false
}

// SetReferrer gets a reference to the given string and assigns it to the Referrer field.
func (o *RegisterRequest) SetReferrer(v string) {
	o.Referrer = &v
}

// GetTos returns the Tos field value if set, zero value otherwise.
func (o *RegisterRequest) GetTos() string {
	if o == nil || IsNil(o.Tos) {
		var ret string
		return ret
	}
	return *o.Tos
}

// GetTosOk returns a tuple with the Tos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetTosOk() (*string, bool) {
	if o == nil || IsNil(o.Tos) {
		return nil, false
	}
	return o.Tos, true
}

// HasTos returns a boolean if a field has been set.
func (o *RegisterRequest) HasTos() bool {
	if o != nil && !IsNil(o.Tos) {
		return true
	}

	return false
}

// SetTos gets a reference to the given string and assigns it to the Tos field.
func (o *RegisterRequest) SetTos(v string) {
	o.Tos = &v
}

// GetExpired returns the Expired field value if set, zero value otherwise.
func (o *RegisterRequest) GetExpired() string {
	if o == nil || IsNil(o.Expired) {
		var ret string
		return ret
	}
	return *o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetExpiredOk() (*string, bool) {
	if o == nil || IsNil(o.Expired) {
		return nil, false
	}
	return o.Expired, true
}

// HasExpired returns a boolean if a field has been set.
func (o *RegisterRequest) HasExpired() bool {
	if o != nil && !IsNil(o.Expired) {
		return true
	}

	return false
}

// SetExpired gets a reference to the given string and assigns it to the Expired field.
func (o *RegisterRequest) SetExpired(v string) {
	o.Expired = &v
}

// GetSerialNumber returns the SerialNumber field value
func (o *RegisterRequest) GetSerialNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetSerialNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SerialNumber, true
}

// SetSerialNumber sets field value
func (o *RegisterRequest) SetSerialNumber(v string) {
	o.SerialNumber = v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *RegisterRequest) GetOsVersion() string {
	if o == nil || IsNil(o.OsVersion) {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetOsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OsVersion) {
		return nil, false
	}
	return o.OsVersion, true
}

// HasOsVersion returns a boolean if a field has been set.
func (o *RegisterRequest) HasOsVersion() bool {
	if o != nil && !IsNil(o.OsVersion) {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *RegisterRequest) SetOsVersion(v string) {
	o.OsVersion = &v
}

// GetKeyType returns the KeyType field value if set, zero value otherwise.
func (o *RegisterRequest) GetKeyType() string {
	if o == nil || IsNil(o.KeyType) {
		var ret string
		return ret
	}
	return *o.KeyType
}

// GetKeyTypeOk returns a tuple with the KeyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetKeyTypeOk() (*string, bool) {
	if o == nil || IsNil(o.KeyType) {
		return nil, false
	}
	return o.KeyType, true
}

// HasKeyType returns a boolean if a field has been set.
func (o *RegisterRequest) HasKeyType() bool {
	if o != nil && !IsNil(o.KeyType) {
		return true
	}

	return false
}

// SetKeyType gets a reference to the given string and assigns it to the KeyType field.
func (o *RegisterRequest) SetKeyType(v string) {
	o.KeyType = &v
}

// GetTunnelType returns the TunnelType field value if set, zero value otherwise.
func (o *RegisterRequest) GetTunnelType() string {
	if o == nil || IsNil(o.TunnelType) {
		var ret string
		return ret
	}
	return *o.TunnelType
}

// GetTunnelTypeOk returns a tuple with the TunnelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterRequest) GetTunnelTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TunnelType) {
		return nil, false
	}
	return o.TunnelType, true
}

// HasTunnelType returns a boolean if a field has been set.
func (o *RegisterRequest) HasTunnelType() bool {
	if o != nil && !IsNil(o.TunnelType) {
		return true
	}

	return false
}

// SetTunnelType gets a reference to the given string and assigns it to the TunnelType field.
func (o *RegisterRequest) SetTunnelType(v string) {
	o.TunnelType = &v
}

func (o RegisterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fcm_token"] = o.FcmToken
	toSerialize["install_id"] = o.InstallId
	toSerialize["key"] = o.Key
	toSerialize["locale"] = o.Locale
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Referrer) {
		toSerialize["referrer"] = o.Referrer
	}
	if !IsNil(o.Tos) {
		toSerialize["tos"] = o.Tos
	}
	if !IsNil(o.Expired) {
		toSerialize["expired"] = o.Expired
	}
	toSerialize["serial_number"] = o.SerialNumber
	if !IsNil(o.OsVersion) {
		toSerialize["os_version"] = o.OsVersion
	}
	if !IsNil(o.KeyType) {
		toSerialize["key_type"] = o.KeyType
	}
	if !IsNil(o.TunnelType) {
		toSerialize["tunnel_type"] = o.TunnelType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RegisterRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fcm_token",
		"install_id",
		"key",
		"locale",
		"serial_number",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterRequest := _RegisterRequest{}

	err = json.Unmarshal(data, &varRegisterRequest)

	if err != nil {
		return err
	}

	*o = RegisterRequest(varRegisterRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fcm_token")
		delete(additionalProperties, "install_id")
		delete(additionalProperties, "key")
		delete(additionalProperties, "locale")
		delete(additionalProperties, "model")
		delete(additionalProperties, "referrer")
		delete(additionalProperties, "tos")
		delete(additionalProperties, "expired")
		delete(additionalProperties, "serial_number")
		delete(additionalProperties, "os_version")
		delete(additionalProperties, "key_type")
		delete(additionalProperties, "tunnel_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRegisterRequest struct {
	value *RegisterRequest
	isSet bool
}

func (v NullableRegisterRequest) Get() *RegisterRequest {
	return v.value
}

func (v *NullableRegisterRequest) Set(val *RegisterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterRequest(val *RegisterRequest) *NullableRegisterRequest {
	return &NullableRegisterRequest{value: val, isSet: true}
}

func (v NullableRegisterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


