/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetClientConfig200ResponseNetworks struct for GetClientConfig200ResponseNetworks
type GetClientConfig200ResponseNetworks struct {
	V4 []GetClientConfig200ResponseNetworksV4 `json:"v4"`
	V6 []GetClientConfig200ResponseNetworksV6 `json:"v6"`
}
