/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetClientConfig200ResponseNetworks1V4 struct for GetClientConfig200ResponseNetworks1V4
type GetClientConfig200ResponseNetworks1V4 struct {
	Address string `json:"address"`
	Netmask string `json:"netmask"`
}

// NewGetClientConfig200ResponseNetworks1V4 instantiates a new GetClientConfig200ResponseNetworks1V4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetClientConfig200ResponseNetworks1V4(address string, netmask string, ) *GetClientConfig200ResponseNetworks1V4 {
	this := GetClientConfig200ResponseNetworks1V4{}
	this.Address = address
	this.Netmask = netmask
	return &this
}

// NewGetClientConfig200ResponseNetworks1V4WithDefaults instantiates a new GetClientConfig200ResponseNetworks1V4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetClientConfig200ResponseNetworks1V4WithDefaults() *GetClientConfig200ResponseNetworks1V4 {
	this := GetClientConfig200ResponseNetworks1V4{}
	return &this
}

// GetAddress returns the Address field value
func (o *GetClientConfig200ResponseNetworks1V4) GetAddress() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseNetworks1V4) GetAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *GetClientConfig200ResponseNetworks1V4) SetAddress(v string) {
	o.Address = v
}

// GetNetmask returns the Netmask field value
func (o *GetClientConfig200ResponseNetworks1V4) GetNetmask() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Netmask
}

// GetNetmaskOk returns a tuple with the Netmask field value
// and a boolean to check if the value has been set.
func (o *GetClientConfig200ResponseNetworks1V4) GetNetmaskOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Netmask, true
}

// SetNetmask sets field value
func (o *GetClientConfig200ResponseNetworks1V4) SetNetmask(v string) {
	o.Netmask = v
}

func (o GetClientConfig200ResponseNetworks1V4) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["address"] = o.Address
	}
	if true {
		toSerialize["netmask"] = o.Netmask
	}
	return json.Marshal(toSerialize)
}

type NullableGetClientConfig200ResponseNetworks1V4 struct {
	value *GetClientConfig200ResponseNetworks1V4
	isSet bool
}

func (v NullableGetClientConfig200ResponseNetworks1V4) Get() *GetClientConfig200ResponseNetworks1V4 {
	return v.value
}

func (v *NullableGetClientConfig200ResponseNetworks1V4) Set(val *GetClientConfig200ResponseNetworks1V4) {
	v.value = val
	v.isSet = true
}

func (v NullableGetClientConfig200ResponseNetworks1V4) IsSet() bool {
	return v.isSet
}

func (v *NullableGetClientConfig200ResponseNetworks1V4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetClientConfig200ResponseNetworks1V4(val *GetClientConfig200ResponseNetworks1V4) *NullableGetClientConfig200ResponseNetworks1V4 {
	return &NullableGetClientConfig200ResponseNetworks1V4{value: val, isSet: true}
}

func (v NullableGetClientConfig200ResponseNetworks1V4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetClientConfig200ResponseNetworks1V4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


