/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UpdateBoundDeviceRequest struct for UpdateBoundDeviceRequest
type UpdateBoundDeviceRequest struct {
	Active bool `json:"active,omitempty"`
	Name string `json:"name,omitempty"`
}
