/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PostQuantumSupport the model 'PostQuantumSupport'
type PostQuantumSupport string

// List of PostQuantumSupport
const (
	DISABLED PostQuantumSupport = "disabled"
	ENABLED PostQuantumSupport = "enabled"
	ENABLED_WITH_DOWNGRADES PostQuantumSupport = "enabled_with_downgrades"
)

// All allowed values of PostQuantumSupport enum
var AllowedPostQuantumSupportEnumValues = []PostQuantumSupport{
	"disabled",
	"enabled",
	"enabled_with_downgrades",
}

func (v *PostQuantumSupport) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PostQuantumSupport(value)
	for _, existing := range AllowedPostQuantumSupportEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PostQuantumSupport", value)
}

// NewPostQuantumSupportFromValue returns a pointer to a valid PostQuantumSupport
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPostQuantumSupportFromValue(v string) (*PostQuantumSupport, error) {
	ev := PostQuantumSupport(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PostQuantumSupport: valid values are %v", v, AllowedPostQuantumSupportEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PostQuantumSupport) IsValid() bool {
	for _, existing := range AllowedPostQuantumSupportEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PostQuantumSupport value
func (v PostQuantumSupport) Ptr() *PostQuantumSupport {
	return &v
}

type NullablePostQuantumSupport struct {
	value *PostQuantumSupport
	isSet bool
}

func (v NullablePostQuantumSupport) Get() *PostQuantumSupport {
	return v.value
}

func (v *NullablePostQuantumSupport) Set(val *PostQuantumSupport) {
	v.value = val
	v.isSet = true
}

func (v NullablePostQuantumSupport) IsSet() bool {
	return v.isSet
}

func (v *NullablePostQuantumSupport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostQuantumSupport(val *PostQuantumSupport) *NullablePostQuantumSupport {
	return &NullablePostQuantumSupport{value: val, isSet: true}
}

func (v NullablePostQuantumSupport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostQuantumSupport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

