/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the GetSourceDevice200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSourceDevice200Response{}

// GetSourceDevice200Response struct for GetSourceDevice200Response
type GetSourceDevice200Response struct {
	Created *time.Time `json:"created,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	FcmToken *string `json:"fcm_token,omitempty"`
	Id string `json:"id"`
	InstallId *string `json:"install_id,omitempty"`
	Key *string `json:"key,omitempty"`
	Locale *string `json:"locale,omitempty"`
	Model *string `json:"model,omitempty"`
	Manufacturer *string `json:"manufacturer,omitempty"`
	Name *string `json:"name,omitempty"`
	OsVersion *string `json:"os_version,omitempty"`
	Place *int32 `json:"place,omitempty"`
	SerialNumber *string `json:"serial_number,omitempty"`
	DeviceId *string `json:"device_id,omitempty"`
	Tos *time.Time `json:"tos,omitempty"`
	Type *string `json:"type,omitempty"`
	Updated *time.Time `json:"updated,omitempty"`
	WaitlistEnabled *bool `json:"waitlist_enabled,omitempty"`
	WarpEnabled *bool `json:"warp_enabled,omitempty"`
	Account Account `json:"account"`
	Config *Config `json:"config,omitempty"`
	Policy *Policy `json:"policy,omitempty"`
	OverrideCodes *OverrideCodes `json:"override_codes,omitempty"`
	AlternateNetworks []AlternateNetwork `json:"alternate_networks,omitempty"`
	DexTests []DexTest `json:"dex_tests,omitempty"`
	KeyType string `json:"key_type"`
	TunnelType string `json:"tunnel_type"`
	AdditionalProperties map[string]interface{}
}

type _GetSourceDevice200Response GetSourceDevice200Response

// NewGetSourceDevice200Response instantiates a new GetSourceDevice200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSourceDevice200Response(id string, account Account, keyType string, tunnelType string) *GetSourceDevice200Response {
	this := GetSourceDevice200Response{}
	this.Id = id
	this.Account = account
	this.KeyType = keyType
	this.TunnelType = tunnelType
	return &this
}

// NewGetSourceDevice200ResponseWithDefaults instantiates a new GetSourceDevice200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSourceDevice200ResponseWithDefaults() *GetSourceDevice200Response {
	this := GetSourceDevice200Response{}
	return &this
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *GetSourceDevice200Response) SetCreated(v time.Time) {
	o.Created = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *GetSourceDevice200Response) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetFcmToken returns the FcmToken field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetFcmToken() string {
	if o == nil || IsNil(o.FcmToken) {
		var ret string
		return ret
	}
	return *o.FcmToken
}

// GetFcmTokenOk returns a tuple with the FcmToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetFcmTokenOk() (*string, bool) {
	if o == nil || IsNil(o.FcmToken) {
		return nil, false
	}
	return o.FcmToken, true
}

// HasFcmToken returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasFcmToken() bool {
	if o != nil && !IsNil(o.FcmToken) {
		return true
	}

	return false
}

// SetFcmToken gets a reference to the given string and assigns it to the FcmToken field.
func (o *GetSourceDevice200Response) SetFcmToken(v string) {
	o.FcmToken = &v
}

// GetId returns the Id field value
func (o *GetSourceDevice200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetSourceDevice200Response) SetId(v string) {
	o.Id = v
}

// GetInstallId returns the InstallId field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetInstallId() string {
	if o == nil || IsNil(o.InstallId) {
		var ret string
		return ret
	}
	return *o.InstallId
}

// GetInstallIdOk returns a tuple with the InstallId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetInstallIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstallId) {
		return nil, false
	}
	return o.InstallId, true
}

// HasInstallId returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasInstallId() bool {
	if o != nil && !IsNil(o.InstallId) {
		return true
	}

	return false
}

// SetInstallId gets a reference to the given string and assigns it to the InstallId field.
func (o *GetSourceDevice200Response) SetInstallId(v string) {
	o.InstallId = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *GetSourceDevice200Response) SetKey(v string) {
	o.Key = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *GetSourceDevice200Response) SetLocale(v string) {
	o.Locale = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *GetSourceDevice200Response) SetModel(v string) {
	o.Model = &v
}

// GetManufacturer returns the Manufacturer field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetManufacturer() string {
	if o == nil || IsNil(o.Manufacturer) {
		var ret string
		return ret
	}
	return *o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetManufacturerOk() (*string, bool) {
	if o == nil || IsNil(o.Manufacturer) {
		return nil, false
	}
	return o.Manufacturer, true
}

// HasManufacturer returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasManufacturer() bool {
	if o != nil && !IsNil(o.Manufacturer) {
		return true
	}

	return false
}

// SetManufacturer gets a reference to the given string and assigns it to the Manufacturer field.
func (o *GetSourceDevice200Response) SetManufacturer(v string) {
	o.Manufacturer = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetSourceDevice200Response) SetName(v string) {
	o.Name = &v
}

// GetOsVersion returns the OsVersion field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetOsVersion() string {
	if o == nil || IsNil(o.OsVersion) {
		var ret string
		return ret
	}
	return *o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetOsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.OsVersion) {
		return nil, false
	}
	return o.OsVersion, true
}

// HasOsVersion returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasOsVersion() bool {
	if o != nil && !IsNil(o.OsVersion) {
		return true
	}

	return false
}

// SetOsVersion gets a reference to the given string and assigns it to the OsVersion field.
func (o *GetSourceDevice200Response) SetOsVersion(v string) {
	o.OsVersion = &v
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetPlace() int32 {
	if o == nil || IsNil(o.Place) {
		var ret int32
		return ret
	}
	return *o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetPlaceOk() (*int32, bool) {
	if o == nil || IsNil(o.Place) {
		return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasPlace() bool {
	if o != nil && !IsNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given int32 and assigns it to the Place field.
func (o *GetSourceDevice200Response) SetPlace(v int32) {
	o.Place = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *GetSourceDevice200Response) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetDeviceId() string {
	if o == nil || IsNil(o.DeviceId) {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetDeviceIdOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceId) {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasDeviceId() bool {
	if o != nil && !IsNil(o.DeviceId) {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *GetSourceDevice200Response) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetTos returns the Tos field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetTos() time.Time {
	if o == nil || IsNil(o.Tos) {
		var ret time.Time
		return ret
	}
	return *o.Tos
}

// GetTosOk returns a tuple with the Tos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetTosOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Tos) {
		return nil, false
	}
	return o.Tos, true
}

// HasTos returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasTos() bool {
	if o != nil && !IsNil(o.Tos) {
		return true
	}

	return false
}

// SetTos gets a reference to the given time.Time and assigns it to the Tos field.
func (o *GetSourceDevice200Response) SetTos(v time.Time) {
	o.Tos = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetSourceDevice200Response) SetType(v string) {
	o.Type = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *GetSourceDevice200Response) SetUpdated(v time.Time) {
	o.Updated = &v
}

// GetWaitlistEnabled returns the WaitlistEnabled field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetWaitlistEnabled() bool {
	if o == nil || IsNil(o.WaitlistEnabled) {
		var ret bool
		return ret
	}
	return *o.WaitlistEnabled
}

// GetWaitlistEnabledOk returns a tuple with the WaitlistEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetWaitlistEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WaitlistEnabled) {
		return nil, false
	}
	return o.WaitlistEnabled, true
}

// HasWaitlistEnabled returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasWaitlistEnabled() bool {
	if o != nil && !IsNil(o.WaitlistEnabled) {
		return true
	}

	return false
}

// SetWaitlistEnabled gets a reference to the given bool and assigns it to the WaitlistEnabled field.
func (o *GetSourceDevice200Response) SetWaitlistEnabled(v bool) {
	o.WaitlistEnabled = &v
}

// GetWarpEnabled returns the WarpEnabled field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetWarpEnabled() bool {
	if o == nil || IsNil(o.WarpEnabled) {
		var ret bool
		return ret
	}
	return *o.WarpEnabled
}

// GetWarpEnabledOk returns a tuple with the WarpEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetWarpEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WarpEnabled) {
		return nil, false
	}
	return o.WarpEnabled, true
}

// HasWarpEnabled returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasWarpEnabled() bool {
	if o != nil && !IsNil(o.WarpEnabled) {
		return true
	}

	return false
}

// SetWarpEnabled gets a reference to the given bool and assigns it to the WarpEnabled field.
func (o *GetSourceDevice200Response) SetWarpEnabled(v bool) {
	o.WarpEnabled = &v
}

// GetAccount returns the Account field value
func (o *GetSourceDevice200Response) GetAccount() Account {
	if o == nil {
		var ret Account
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetAccountOk() (*Account, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *GetSourceDevice200Response) SetAccount(v Account) {
	o.Account = v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetConfig() Config {
	if o == nil || IsNil(o.Config) {
		var ret Config
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetConfigOk() (*Config, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given Config and assigns it to the Config field.
func (o *GetSourceDevice200Response) SetConfig(v Config) {
	o.Config = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetPolicy() Policy {
	if o == nil || IsNil(o.Policy) {
		var ret Policy
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetPolicyOk() (*Policy, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given Policy and assigns it to the Policy field.
func (o *GetSourceDevice200Response) SetPolicy(v Policy) {
	o.Policy = &v
}

// GetOverrideCodes returns the OverrideCodes field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetOverrideCodes() OverrideCodes {
	if o == nil || IsNil(o.OverrideCodes) {
		var ret OverrideCodes
		return ret
	}
	return *o.OverrideCodes
}

// GetOverrideCodesOk returns a tuple with the OverrideCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetOverrideCodesOk() (*OverrideCodes, bool) {
	if o == nil || IsNil(o.OverrideCodes) {
		return nil, false
	}
	return o.OverrideCodes, true
}

// HasOverrideCodes returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasOverrideCodes() bool {
	if o != nil && !IsNil(o.OverrideCodes) {
		return true
	}

	return false
}

// SetOverrideCodes gets a reference to the given OverrideCodes and assigns it to the OverrideCodes field.
func (o *GetSourceDevice200Response) SetOverrideCodes(v OverrideCodes) {
	o.OverrideCodes = &v
}

// GetAlternateNetworks returns the AlternateNetworks field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetAlternateNetworks() []AlternateNetwork {
	if o == nil || IsNil(o.AlternateNetworks) {
		var ret []AlternateNetwork
		return ret
	}
	return o.AlternateNetworks
}

// GetAlternateNetworksOk returns a tuple with the AlternateNetworks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetAlternateNetworksOk() ([]AlternateNetwork, bool) {
	if o == nil || IsNil(o.AlternateNetworks) {
		return nil, false
	}
	return o.AlternateNetworks, true
}

// HasAlternateNetworks returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasAlternateNetworks() bool {
	if o != nil && !IsNil(o.AlternateNetworks) {
		return true
	}

	return false
}

// SetAlternateNetworks gets a reference to the given []AlternateNetwork and assigns it to the AlternateNetworks field.
func (o *GetSourceDevice200Response) SetAlternateNetworks(v []AlternateNetwork) {
	o.AlternateNetworks = v
}

// GetDexTests returns the DexTests field value if set, zero value otherwise.
func (o *GetSourceDevice200Response) GetDexTests() []DexTest {
	if o == nil || IsNil(o.DexTests) {
		var ret []DexTest
		return ret
	}
	return o.DexTests
}

// GetDexTestsOk returns a tuple with the DexTests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetDexTestsOk() ([]DexTest, bool) {
	if o == nil || IsNil(o.DexTests) {
		return nil, false
	}
	return o.DexTests, true
}

// HasDexTests returns a boolean if a field has been set.
func (o *GetSourceDevice200Response) HasDexTests() bool {
	if o != nil && !IsNil(o.DexTests) {
		return true
	}

	return false
}

// SetDexTests gets a reference to the given []DexTest and assigns it to the DexTests field.
func (o *GetSourceDevice200Response) SetDexTests(v []DexTest) {
	o.DexTests = v
}

// GetKeyType returns the KeyType field value
func (o *GetSourceDevice200Response) GetKeyType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyType
}

// GetKeyTypeOk returns a tuple with the KeyType field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetKeyTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyType, true
}

// SetKeyType sets field value
func (o *GetSourceDevice200Response) SetKeyType(v string) {
	o.KeyType = v
}

// GetTunnelType returns the TunnelType field value
func (o *GetSourceDevice200Response) GetTunnelType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelType
}

// GetTunnelTypeOk returns a tuple with the TunnelType field value
// and a boolean to check if the value has been set.
func (o *GetSourceDevice200Response) GetTunnelTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelType, true
}

// SetTunnelType sets field value
func (o *GetSourceDevice200Response) SetTunnelType(v string) {
	o.TunnelType = v
}

func (o GetSourceDevice200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSourceDevice200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.FcmToken) {
		toSerialize["fcm_token"] = o.FcmToken
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.InstallId) {
		toSerialize["install_id"] = o.InstallId
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Manufacturer) {
		toSerialize["manufacturer"] = o.Manufacturer
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OsVersion) {
		toSerialize["os_version"] = o.OsVersion
	}
	if !IsNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	if !IsNil(o.SerialNumber) {
		toSerialize["serial_number"] = o.SerialNumber
	}
	if !IsNil(o.DeviceId) {
		toSerialize["device_id"] = o.DeviceId
	}
	if !IsNil(o.Tos) {
		toSerialize["tos"] = o.Tos
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	if !IsNil(o.WaitlistEnabled) {
		toSerialize["waitlist_enabled"] = o.WaitlistEnabled
	}
	if !IsNil(o.WarpEnabled) {
		toSerialize["warp_enabled"] = o.WarpEnabled
	}
	toSerialize["account"] = o.Account
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.OverrideCodes) {
		toSerialize["override_codes"] = o.OverrideCodes
	}
	if !IsNil(o.AlternateNetworks) {
		toSerialize["alternate_networks"] = o.AlternateNetworks
	}
	if !IsNil(o.DexTests) {
		toSerialize["dex_tests"] = o.DexTests
	}
	toSerialize["key_type"] = o.KeyType
	toSerialize["tunnel_type"] = o.TunnelType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSourceDevice200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"account",
		"key_type",
		"tunnel_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSourceDevice200Response := _GetSourceDevice200Response{}

	err = json.Unmarshal(data, &varGetSourceDevice200Response)

	if err != nil {
		return err
	}

	*o = GetSourceDevice200Response(varGetSourceDevice200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "fcm_token")
		delete(additionalProperties, "id")
		delete(additionalProperties, "install_id")
		delete(additionalProperties, "key")
		delete(additionalProperties, "locale")
		delete(additionalProperties, "model")
		delete(additionalProperties, "manufacturer")
		delete(additionalProperties, "name")
		delete(additionalProperties, "os_version")
		delete(additionalProperties, "place")
		delete(additionalProperties, "serial_number")
		delete(additionalProperties, "device_id")
		delete(additionalProperties, "tos")
		delete(additionalProperties, "type")
		delete(additionalProperties, "updated")
		delete(additionalProperties, "waitlist_enabled")
		delete(additionalProperties, "warp_enabled")
		delete(additionalProperties, "account")
		delete(additionalProperties, "config")
		delete(additionalProperties, "policy")
		delete(additionalProperties, "override_codes")
		delete(additionalProperties, "alternate_networks")
		delete(additionalProperties, "dex_tests")
		delete(additionalProperties, "key_type")
		delete(additionalProperties, "tunnel_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSourceDevice200Response struct {
	value *GetSourceDevice200Response
	isSet bool
}

func (v NullableGetSourceDevice200Response) Get() *GetSourceDevice200Response {
	return v.value
}

func (v *NullableGetSourceDevice200Response) Set(val *GetSourceDevice200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSourceDevice200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSourceDevice200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSourceDevice200Response(val *GetSourceDevice200Response) *NullableGetSourceDevice200Response {
	return &NullableGetSourceDevice200Response{value: val, isSet: true}
}

func (v NullableGetSourceDevice200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSourceDevice200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


