/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClientConfigDenylistInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientConfigDenylistInner{}

// ClientConfigDenylistInner struct for ClientConfigDenylistInner
type ClientConfigDenylistInner struct {
	AndroidPackages []string `json:"android-packages,omitempty"`
	Name string `json:"name"`
	Networks *ClientConfigDenylistInnerNetworks `json:"networks,omitempty"`
	Visible bool `json:"visible"`
	AdditionalProperties map[string]interface{}
}

type _ClientConfigDenylistInner ClientConfigDenylistInner

// NewClientConfigDenylistInner instantiates a new ClientConfigDenylistInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientConfigDenylistInner(name string, visible bool) *ClientConfigDenylistInner {
	this := ClientConfigDenylistInner{}
	this.Name = name
	this.Visible = visible
	return &this
}

// NewClientConfigDenylistInnerWithDefaults instantiates a new ClientConfigDenylistInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientConfigDenylistInnerWithDefaults() *ClientConfigDenylistInner {
	this := ClientConfigDenylistInner{}
	return &this
}

// GetAndroidPackages returns the AndroidPackages field value if set, zero value otherwise.
func (o *ClientConfigDenylistInner) GetAndroidPackages() []string {
	if o == nil || IsNil(o.AndroidPackages) {
		var ret []string
		return ret
	}
	return o.AndroidPackages
}

// GetAndroidPackagesOk returns a tuple with the AndroidPackages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientConfigDenylistInner) GetAndroidPackagesOk() ([]string, bool) {
	if o == nil || IsNil(o.AndroidPackages) {
		return nil, false
	}
	return o.AndroidPackages, true
}

// HasAndroidPackages returns a boolean if a field has been set.
func (o *ClientConfigDenylistInner) HasAndroidPackages() bool {
	if o != nil && !IsNil(o.AndroidPackages) {
		return true
	}

	return false
}

// SetAndroidPackages gets a reference to the given []string and assigns it to the AndroidPackages field.
func (o *ClientConfigDenylistInner) SetAndroidPackages(v []string) {
	o.AndroidPackages = v
}

// GetName returns the Name field value
func (o *ClientConfigDenylistInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClientConfigDenylistInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClientConfigDenylistInner) SetName(v string) {
	o.Name = v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *ClientConfigDenylistInner) GetNetworks() ClientConfigDenylistInnerNetworks {
	if o == nil || IsNil(o.Networks) {
		var ret ClientConfigDenylistInnerNetworks
		return ret
	}
	return *o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientConfigDenylistInner) GetNetworksOk() (*ClientConfigDenylistInnerNetworks, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *ClientConfigDenylistInner) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given ClientConfigDenylistInnerNetworks and assigns it to the Networks field.
func (o *ClientConfigDenylistInner) SetNetworks(v ClientConfigDenylistInnerNetworks) {
	o.Networks = &v
}

// GetVisible returns the Visible field value
func (o *ClientConfigDenylistInner) GetVisible() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Visible
}

// GetVisibleOk returns a tuple with the Visible field value
// and a boolean to check if the value has been set.
func (o *ClientConfigDenylistInner) GetVisibleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visible, true
}

// SetVisible sets field value
func (o *ClientConfigDenylistInner) SetVisible(v bool) {
	o.Visible = v
}

func (o ClientConfigDenylistInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientConfigDenylistInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AndroidPackages) {
		toSerialize["android-packages"] = o.AndroidPackages
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	toSerialize["visible"] = o.Visible

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClientConfigDenylistInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"visible",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientConfigDenylistInner := _ClientConfigDenylistInner{}

	err = json.Unmarshal(data, &varClientConfigDenylistInner)

	if err != nil {
		return err
	}

	*o = ClientConfigDenylistInner(varClientConfigDenylistInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "android-packages")
		delete(additionalProperties, "name")
		delete(additionalProperties, "networks")
		delete(additionalProperties, "visible")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClientConfigDenylistInner struct {
	value *ClientConfigDenylistInner
	isSet bool
}

func (v NullableClientConfigDenylistInner) Get() *ClientConfigDenylistInner {
	return v.value
}

func (v *NullableClientConfigDenylistInner) Set(val *ClientConfigDenylistInner) {
	v.value = val
	v.isSet = true
}

func (v NullableClientConfigDenylistInner) IsSet() bool {
	return v.isSet
}

func (v *NullableClientConfigDenylistInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientConfigDenylistInner(val *ClientConfigDenylistInner) *NullableClientConfigDenylistInner {
	return &NullableClientConfigDenylistInner{value: val, isSet: true}
}

func (v NullableClientConfigDenylistInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientConfigDenylistInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


