/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Register200Response struct for Register200Response
type Register200Response struct {
	Account Register200ResponseAccount `json:"account"`
	Config GetSourceDevice200ResponseConfig `json:"config"`
	Created string `json:"created"`
	Enabled bool `json:"enabled"`
	FcmToken string `json:"fcm_token"`
	Id string `json:"id"`
	InstallId string `json:"install_id"`
	Key string `json:"key"`
	Locale string `json:"locale"`
	Model string `json:"model"`
	Name string `json:"name"`
	Place float32 `json:"place"`
	Token string `json:"token"`
	Tos string `json:"tos"`
	Type string `json:"type"`
	Updated string `json:"updated"`
	WaitlistEnabled bool `json:"waitlist_enabled"`
	WarpEnabled bool `json:"warp_enabled"`
}
