/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 536
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateSourceDevice200Response struct for UpdateSourceDevice200Response
type UpdateSourceDevice200Response struct {
	Account UpdateSourceDevice200ResponseAccount `json:"account"`
	Config GetSourceDevice200ResponseConfig `json:"config"`
	Created string `json:"created"`
	Enabled bool `json:"enabled"`
	FcmToken string `json:"fcm_token"`
	Id string `json:"id"`
	InstallId string `json:"install_id"`
	Key string `json:"key"`
	Locale string `json:"locale"`
	Model string `json:"model"`
	Name string `json:"name"`
	Place float32 `json:"place"`
	Tos string `json:"tos"`
	Type string `json:"type"`
	Updated string `json:"updated"`
	WaitlistEnabled bool `json:"waitlist_enabled"`
	WarpEnabled bool `json:"warp_enabled"`
}

// NewUpdateSourceDevice200Response instantiates a new UpdateSourceDevice200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSourceDevice200Response(account UpdateSourceDevice200ResponseAccount, config GetSourceDevice200ResponseConfig, created string, enabled bool, fcmToken string, id string, installId string, key string, locale string, model string, name string, place float32, tos string, type_ string, updated string, waitlistEnabled bool, warpEnabled bool, ) *UpdateSourceDevice200Response {
	this := UpdateSourceDevice200Response{}
	this.Account = account
	this.Config = config
	this.Created = created
	this.Enabled = enabled
	this.FcmToken = fcmToken
	this.Id = id
	this.InstallId = installId
	this.Key = key
	this.Locale = locale
	this.Model = model
	this.Name = name
	this.Place = place
	this.Tos = tos
	this.Type = type_
	this.Updated = updated
	this.WaitlistEnabled = waitlistEnabled
	this.WarpEnabled = warpEnabled
	return &this
}

// NewUpdateSourceDevice200ResponseWithDefaults instantiates a new UpdateSourceDevice200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSourceDevice200ResponseWithDefaults() *UpdateSourceDevice200Response {
	this := UpdateSourceDevice200Response{}
	return &this
}

// GetAccount returns the Account field value
func (o *UpdateSourceDevice200Response) GetAccount() UpdateSourceDevice200ResponseAccount {
	if o == nil  {
		var ret UpdateSourceDevice200ResponseAccount
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetAccountOk() (*UpdateSourceDevice200ResponseAccount, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *UpdateSourceDevice200Response) SetAccount(v UpdateSourceDevice200ResponseAccount) {
	o.Account = v
}

// GetConfig returns the Config field value
func (o *UpdateSourceDevice200Response) GetConfig() GetSourceDevice200ResponseConfig {
	if o == nil  {
		var ret GetSourceDevice200ResponseConfig
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetConfigOk() (*GetSourceDevice200ResponseConfig, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *UpdateSourceDevice200Response) SetConfig(v GetSourceDevice200ResponseConfig) {
	o.Config = v
}

// GetCreated returns the Created field value
func (o *UpdateSourceDevice200Response) GetCreated() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetCreatedOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *UpdateSourceDevice200Response) SetCreated(v string) {
	o.Created = v
}

// GetEnabled returns the Enabled field value
func (o *UpdateSourceDevice200Response) GetEnabled() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *UpdateSourceDevice200Response) SetEnabled(v bool) {
	o.Enabled = v
}

// GetFcmToken returns the FcmToken field value
func (o *UpdateSourceDevice200Response) GetFcmToken() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.FcmToken
}

// GetFcmTokenOk returns a tuple with the FcmToken field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetFcmTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FcmToken, true
}

// SetFcmToken sets field value
func (o *UpdateSourceDevice200Response) SetFcmToken(v string) {
	o.FcmToken = v
}

// GetId returns the Id field value
func (o *UpdateSourceDevice200Response) GetId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateSourceDevice200Response) SetId(v string) {
	o.Id = v
}

// GetInstallId returns the InstallId field value
func (o *UpdateSourceDevice200Response) GetInstallId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.InstallId
}

// GetInstallIdOk returns a tuple with the InstallId field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetInstallIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InstallId, true
}

// SetInstallId sets field value
func (o *UpdateSourceDevice200Response) SetInstallId(v string) {
	o.InstallId = v
}

// GetKey returns the Key field value
func (o *UpdateSourceDevice200Response) GetKey() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetKeyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UpdateSourceDevice200Response) SetKey(v string) {
	o.Key = v
}

// GetLocale returns the Locale field value
func (o *UpdateSourceDevice200Response) GetLocale() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetLocaleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Locale, true
}

// SetLocale sets field value
func (o *UpdateSourceDevice200Response) SetLocale(v string) {
	o.Locale = v
}

// GetModel returns the Model field value
func (o *UpdateSourceDevice200Response) GetModel() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetModelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *UpdateSourceDevice200Response) SetModel(v string) {
	o.Model = v
}

// GetName returns the Name field value
func (o *UpdateSourceDevice200Response) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateSourceDevice200Response) SetName(v string) {
	o.Name = v
}

// GetPlace returns the Place field value
func (o *UpdateSourceDevice200Response) GetPlace() float32 {
	if o == nil  {
		var ret float32
		return ret
	}

	return o.Place
}

// GetPlaceOk returns a tuple with the Place field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetPlaceOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Place, true
}

// SetPlace sets field value
func (o *UpdateSourceDevice200Response) SetPlace(v float32) {
	o.Place = v
}

// GetTos returns the Tos field value
func (o *UpdateSourceDevice200Response) GetTos() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Tos
}

// GetTosOk returns a tuple with the Tos field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetTosOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tos, true
}

// SetTos sets field value
func (o *UpdateSourceDevice200Response) SetTos(v string) {
	o.Tos = v
}

// GetType returns the Type field value
func (o *UpdateSourceDevice200Response) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateSourceDevice200Response) SetType(v string) {
	o.Type = v
}

// GetUpdated returns the Updated field value
func (o *UpdateSourceDevice200Response) GetUpdated() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetUpdatedOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *UpdateSourceDevice200Response) SetUpdated(v string) {
	o.Updated = v
}

// GetWaitlistEnabled returns the WaitlistEnabled field value
func (o *UpdateSourceDevice200Response) GetWaitlistEnabled() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.WaitlistEnabled
}

// GetWaitlistEnabledOk returns a tuple with the WaitlistEnabled field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetWaitlistEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WaitlistEnabled, true
}

// SetWaitlistEnabled sets field value
func (o *UpdateSourceDevice200Response) SetWaitlistEnabled(v bool) {
	o.WaitlistEnabled = v
}

// GetWarpEnabled returns the WarpEnabled field value
func (o *UpdateSourceDevice200Response) GetWarpEnabled() bool {
	if o == nil  {
		var ret bool
		return ret
	}

	return o.WarpEnabled
}

// GetWarpEnabledOk returns a tuple with the WarpEnabled field value
// and a boolean to check if the value has been set.
func (o *UpdateSourceDevice200Response) GetWarpEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WarpEnabled, true
}

// SetWarpEnabled sets field value
func (o *UpdateSourceDevice200Response) SetWarpEnabled(v bool) {
	o.WarpEnabled = v
}

func (o UpdateSourceDevice200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["account"] = o.Account
	}
	if true {
		toSerialize["config"] = o.Config
	}
	if true {
		toSerialize["created"] = o.Created
	}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	if true {
		toSerialize["fcm_token"] = o.FcmToken
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["install_id"] = o.InstallId
	}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["locale"] = o.Locale
	}
	if true {
		toSerialize["model"] = o.Model
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["place"] = o.Place
	}
	if true {
		toSerialize["tos"] = o.Tos
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["updated"] = o.Updated
	}
	if true {
		toSerialize["waitlist_enabled"] = o.WaitlistEnabled
	}
	if true {
		toSerialize["warp_enabled"] = o.WarpEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateSourceDevice200Response struct {
	value *UpdateSourceDevice200Response
	isSet bool
}

func (v NullableUpdateSourceDevice200Response) Get() *UpdateSourceDevice200Response {
	return v.value
}

func (v *NullableUpdateSourceDevice200Response) Set(val *UpdateSourceDevice200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSourceDevice200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSourceDevice200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSourceDevice200Response(val *UpdateSourceDevice200Response) *NullableUpdateSourceDevice200Response {
	return &NullableUpdateSourceDevice200Response{value: val, isSet: true}
}

func (v NullableUpdateSourceDevice200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSourceDevice200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


