/*
Cloudflare WARP API

Cloudflare WARP Android API contract for version 6.38.9 (build 5641)

API version: 5641
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the PolicyIP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyIP{}

// PolicyIP struct for PolicyIP
type PolicyIP struct {
	Ip string `json:"ip"`
	AdditionalProperties map[string]interface{}
}

type _PolicyIP PolicyIP

// NewPolicyIP instantiates a new PolicyIP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyIP(ip string) *PolicyIP {
	this := PolicyIP{}
	this.Ip = ip
	return &this
}

// NewPolicyIPWithDefaults instantiates a new PolicyIP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyIPWithDefaults() *PolicyIP {
	this := PolicyIP{}
	return &this
}

// GetIp returns the Ip field value
func (o *PolicyIP) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *PolicyIP) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *PolicyIP) SetIp(v string) {
	o.Ip = v
}

func (o PolicyIP) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyIP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ip"] = o.Ip

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PolicyIP) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ip",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyIP := _PolicyIP{}

	err = json.Unmarshal(data, &varPolicyIP)

	if err != nil {
		return err
	}

	*o = PolicyIP(varPolicyIP)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ip")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePolicyIP struct {
	value *PolicyIP
	isSet bool
}

func (v NullablePolicyIP) Get() *PolicyIP {
	return v.value
}

func (v *NullablePolicyIP) Set(val *PolicyIP) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyIP) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyIP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyIP(val *PolicyIP) *NullablePolicyIP {
	return &NullablePolicyIP{value: val, isSet: true}
}

func (v NullablePolicyIP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyIP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


