/*
 * untitled API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 513
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetClientConfig200ResponseDenylist struct for GetClientConfig200ResponseDenylist
type GetClientConfig200ResponseDenylist struct {
	AndroidPackages []string `json:"android-packages,omitempty"`
	Name string `json:"name"`
	Networks GetClientConfig200ResponseNetworks `json:"networks,omitempty"`
	Visible bool `json:"visible"`
}
